-- Cardoso Marketing Hub — correção de dados: nomes de produto limpos (sem taglines/instruções)
-- Roda uma vez no SQL Editor (depois de 0001..0005 já terem rodado).
-- A extração automática do catálogo às vezes juntou frases de marketing, instruções de uso
-- ou fragmentos de texto ilegível ao nome do produto. Este patch limpa esses 84 nomes,
-- mantendo só o nome do produto como aparece no catálogo.

update public.products set name = 'FOFILHOTES TRENZINHO' where code = '3082' and name = 'FOFILHOTES TRENZINHO 6 unidades (4 unissex e 2 rosas) +18 meses';
update public.products set name = 'FOFILHOTES ÔNIBUS' where code = '3084' and name = 'FOFILHOTES ÔNIBUS 6 unidades (4 unissex e 2 rosas) +18 meses';
update public.products set name = 'FOFILHOTES CAVALINHO' where code = '3090' and name = 'FOFILHOTES CAVALINHO alt ura';
update public.products set name = 'FOFUSH ENCANTADO UNICÓRNIO' where code = '7203' and name = 'FOFUSH ENCANTADO UNICÓRNIO Ilumine com a lanterna de LED para desenhar na barriga do Fofush!';
update public.products set name = 'FOFUSH FALANTE UNICÓRNIO' where code = '7204' and name = 'FOFUSH FALANTE UNICÓRNIO Grava voz e repete de um jeito super divertido!';
update public.products set name = 'BI-BI-BLUM DIDÁTICO' where code = '7157' and name = 'BI-BI-BLUM DIDÁTICO Carrinhos';
update public.products set name = 'BATERIA TOUCH MUSICAL AZUL' where code = '7197' and name = 'BATERIA TOUCH MUSICAL AZUL 2 em 1';
update public.products set name = 'SAPO MUSICAL' where code = '7109' and name = 'SAPO MUSICAL Veja como a brincadeira acontece!';
update public.products set name = 'PICK-UP SUPER FAST' where code = '7117' and name = 'PICK-UP SUPER FAST Toque para andar!';
update public.products set name = 'DINO RITMO DIVERTIDO' where code = '7158' and name = 'DINO RITMO DIVERTIDO Movimentos divertidos!';
update public.products set name = 'NAVIO PIRATA' where code = '8002' and name = 'NAVIO PIRATA Vem com 30 blocos!';
update public.products set name = 'FAZENDINHA 19 BLOCOS' where code = '8026' and name = 'FAZENDINHA 19 BLOCOS Vem com 19 blocos!';
update public.products set name = 'ESTAÇÃO DE RESGATE 10 BLOCOS' where code = '8025' and name = 'ESTAÇÃO DE RESGATE 10 BLOCOS Vem com 10 blocos!';
update public.products set name = 'GIRAFA DE ATIVIDADES AMARELA COM 15 BLOCOS' where code = '8016' and name = 'GIRAFA DE ATIVIDADES AMARELA COM 15 BLOCOS Vem com 15 blocos!';
update public.products set name = 'BLOCKS BOX ROSA COM 90 BLOCOS' where code = '8011' and name = 'BLOCKS BOX ROSA COM 90 BLOCOS Vem com 90 blocos!';
update public.products set name = 'MESINHA CRIATIVA ROSA COM 20 BLOCOS' where code = '8023' and name = 'MESINHA CRIATIVA ROSA COM 20 BLOCOS Vem com 275A x 550C x 380L 20 blocos!';
update public.products set name = 'TRENZINHO DIDÁTICO 28 PEÇAS' where code = '8015' and name = 'TRENZINHO DIDÁTICO 28 PEÇAS Com 28 peças!';
update public.products set name = 'PIPINICO URSO AZUL CAIXA INDIVIDUAL' where code = '8022' and name = 'PIPINICO URSO AZUL CAIXA INDIVIDUAL Recipiente removível Prático e higiênico!';
update public.products set name = 'MOTO SPEED XR MOTO DE EQUILÍBRIO ROSA' where code = '8030' and name = 'MOTO SPEED XR MOTO DE EQUILÍBRIO ROSA * A cor da embalagem';
update public.products set name = 'TOTOKROSS MOTO DE EQUILÍBRIO ROSA CAIXA INDIVIDUAL' where code = '8017' and name = 'TOTOKROSS MOTO DE Andador de EQUILÍBRIO ROSA CAIXA INDIVIDUAL equilibrio';
update public.products set name = 'TRUCK RIDE ON AMARELA' where code = '8014' and name = 'TRUCK RIDE ON AMARELA Vem com CAIXA INDIVIDUAL 10 blocos! * A cor';
update public.products set name = 'TOTOKINHA SPORT ROSA CAIXA INDIVIDUAL' where code = '6010' and name = 'TOTOKINHA SPORT ROSA CAIXA INDIVIDUAL * cor da embalagem';
update public.products set name = 'TOTOKINHA BOLINHA ROSA CAIXA INDIVIDUAL' where code = '6005' and name = 'TOTOKINHA BOLINHA ROSA CAIXA INDIVIDUAL A língua e os bracinhos se * 1 unidade +18 meses A cor mexem! da 316A x 498C x 283L embalagem individual';
update public.products set name = 'TOTOKINHA CLÁSSICA AZUL CAIXA INDIVIDUAL' where code = '0301' and name = 'TOTOKINHA CLÁSSICA AZUL CAIXA INDIVIDUAL * A cor da embalagem individual';
update public.products set name = 'TOTOKINHA CLÁSSICA ROSA CAIXA INDIVIDUAL' where code = '0300' and name = 'TOTOKINHA CLÁSSICA ROSA CAIXA INDIVIDUAL Um brinquedo que auxilia o desenvolvimento da criança de forma lúdica e divertida.';
update public.products set name = 'TOTOKA PLUS SEM ELETRÔNICO ROSA CAIXA INDIVIDUAL' where code = '6007' and name = 'TOTOKA PLUS SEM ELETRÔNICO ROSA CAIXA INDIVIDUAL **';
update public.products set name = 'TOTOKA PLUS SEM ELETRÔNICO AZUL CAIXA INDIVIDUAL' where code = '6008' and name = 'TOTOKA PLUS SEM ELETRÔNICO AZUL CAIXA INDIVIDUAL **';
update public.products set name = 'TOTOKA BABY TRACTOR CAIXA INDIVIDUAL' where code = '6009' and name = 'TOTOKA BABY TRACTOR CAIXA INDIVIDUAL ** ** Todas as referências desta página são sem eletrônico.';
update public.products set name = 'ACQUA BUBBLE CAIXA INDIVIDUAL' where code = '2019' and name = 'ACQUA BUBBLE CAIXA INDIVIDUAL * A cor da';
update public.products set name = 'COZINHA SONHO DE MENINA CAIXA INDIVIDUAL' where code = '2016' and name = 'COZINHA SONHO DE MENINA CAIXA INDIVIDUAL Torneira lúdica, não sai água de verdade.';
update public.products set name = 'GELADEIRA SONHO DE MENINA CAIXA INDIVIDUAL' where code = '2015' and name = 'GELADEIRA SONHO DE MENINA CAIXA INDIVIDUAL * A cor da embalagem';
update public.products set name = 'GELADEIRA GELA SORVETINHO CAIXA INDIVIDUAL' where code = '2017' and name = 'GELADEIRA GELA SORVETINHO CAIXA INDIVIDUAL 1º Puxe a 486A x 255C x 202L casquinha 2º Aperte o botão 3º Tire o Sorvetinho';
update public.products set name = 'CELEBRIDADES ESCOVA & PENTEADO' where code = '7186' and name = 'CELEBRIDADES ESCOVA & PENTEADO *Não funciona como';
update public.products set name = 'OPEN TRACKS TRATOR ESCAVADEIRA' where code = '1060' and name = 'OPEN TRACKS TRATOR ESCAVADEIRA 233A x 560C x 195L +,''#-"';
update public.products set name = 'OPEN TRACKS TRATOR RETROESCAVADEIRA' where code = '1059' and name = 'OPEN TRACKS TRATOR RETROESCAVADEIRA 235A x 650C x 195L *+,&-';
update public.products set name = 'TANDY TRACTOR' where code = '1017' and name = 'TANDY TRACTOR Um super caminhão basculante e carregadeira com caçamba e braços articulados!';
update public.products set name = 'TANDY BOMBEIRO' where code = '1049' and name = 'TANDY BOMBEIRO Um caminhão de bombeiro equipado com cones, escadas retráteis, maca de salvamento e extintores!';
update public.products set name = 'ELETRONIC PARKING BOMBEIRO' where code = '7193' and name = 'ELETRONIC PARKING BOMBEIRO Elevador eletrônico!';
update public.products set name = 'TOTOKINHA PRINCESAS' where code = '3124' and name = 'LANÇAMENTO! TOTOKINHA PRINCESAS';
update public.products set name = 'PATINETE BLUEY' where code = '7229' and name = 'LANÇAMENTO! PATINETE BLUEY* .seõçaretla a';
update public.products set name = 'TOTOKINHA BLUEY' where code = '3123' and name = 'LANÇAMENTO! TOTOKINHA BLUEY*';
update public.products set name = 'MINIATURAS GALINHA PINTADINHA' where code = '3038' and name = 'MINIATURAS GALINHA PINTADINHA 5cm al tura';
update public.products set name = 'TOTOKINHA POCOYO COM BONECO' where code = '3063' and name = 'TOTOKINHA POCOYO COM BONECO (licenciado)';
update public.products set name = 'COM BONECO CAIXA INDIVIDUAL' where code = '6012' and name = 'COM BONECO CAIXA INDIVIDUAL (licenciado) * A cor 1 unidade +18 meses da embalagem 316A x 510C x 283L';
update public.products set name = 'TOTOKINHA ELLY COM BONECO' where code = '3068' and name = 'TOTOKINHA ELLY COM BONECO (licenciado)';
update public.products set name = 'BONECO DE VINIL POCOYO' where code = '0275' and name = 'BONECO DE VINIL POCOYO (licenciado)';
update public.products set name = 'BONECO DE VINIL SONEQUITA' where code = '3049' and name = 'BONECO DE VINIL SONEQUITA (licenciado)';
update public.products set name = 'BONECO DE VINIL FRED' where code = '3048' and name = 'BONECO DE VINIL FRED (licenciado)';
update public.products set name = 'BONECO DE VINIL NINA' where code = '3021' and name = 'BONECO DE VINIL NINA (licenciado)';
update public.products set name = 'BONECO DE VINIL PATO' where code = '0282' and name = 'BONECO DE VINIL PATO (licenciado)';
update public.products set name = 'BONECO DE VINIL ELLY' where code = '3011' and name = 'BONECO DE VINIL ELLY (licenciado)';
update public.products set name = 'BONECO DE VINIL LOULA' where code = '0281' and name = 'BONECO DE VINIL LOULA (licenciado)';
update public.products set name = 'BONECO DE PELÚCIA E VINIL POCOYO' where code = '3065' and name = 'BONECO DE PELÚCIA E VINIL POCOYO (licenciado)';
update public.products set name = 'BONECO DE PELÚCIA POCOYO' where code = '3064' and name = 'BONECO DE PELÚCIA POCOYO (licenciado) Fofinho e macio Sem embalagem';
update public.products set name = 'BONECO DE VINIL POCOYO GRANDE' where code = '3050' and name = 'BONECO DE VINIL POCOYO GRANDE (licenciado)';
update public.products set name = 'BONECO DE VINIL PATO GRANDE' where code = '3052' and name = 'BONECO DE VINIL PATO GRANDE (licenciado)';
update public.products set name = 'BONECO DE VINIL ELLY GRANDE' where code = '3051' and name = 'BONECO DE VINIL ELLY GRANDE (licenciado)';
update public.products set name = 'MINIATURAS POCOYO' where code = '3013' and name = 'MINIATURAS POCOYO (licenciado)';
update public.products set name = 'TAMBOR POCOYO' where code = '0263' and name = 'TAMBOR POCOYO (licenciado)';
update public.products set name = 'TAMBORETE POCOYO' where code = '0266' and name = 'TAMBORETE POCOYO (licenciado)';
update public.products set name = 'GUITARRA POCOYO' where code = '0272' and name = 'GUITARRA POCOYO (licenciado)';
update public.products set name = 'MESINHA DE ATIVIDADES ROSA CAIXA INDIVIDUAL' where code = '3053' and name = 'MESINHA DE ATIVIDADES ROSA CAIXA INDIVIDUAL +18 meses BRINQUEDO';
update public.products set name = 'BAUDUXO DIDÁTICO ROSA SEM EMBALAGEM' where code = '3055' and name = 'BAUDUXO DIDÁTICO ROSA SEM EMBALAGEM 4 unidades +18 meses BRINQUEDO COM BRAILLE';
update public.products set name = 'PIPINICO ROSA CAIXA INDIVIDUAL' where code = '9506' and name = 'PIPINICO ROSA CAIXA INDIVIDUAL R$ Com tampa! Apoio lateral para maior estabilidade da criança Formato anatômico';
update public.products set name = 'PIPINICO AZUL CAIXA INDIVIDUAL' where code = '9505' and name = 'PIPINICO AZUL CAIXA INDIVIDUAL * A cor da embalagem individual';
update public.products set name = 'PET CLUB HORA DO BANHO' where code = '7126' and name = 'PET CLUB HORA DO BANHO em';
update public.products set name = 'DOCE COZINHA FOGÃOZINHO' where code = '2011' and name = 'DOCE COZINHA FOGÃOZINHO ( & "';
update public.products set name = 'DOCE COZINHA FAZ-DE-CONTA' where code = '2010' and name = 'DOCE COZINHA FAZ-DE-CONTA ( & "';
update public.products set name = 'DINOCAR COM CARRINHOS' where code = '7129' and name = 'DINOCAR COM CARRINHOS Com 2 dinossauros vinil em miniatura';
update public.products set name = 'Display Robô-Blocks Serviço' where code = '7171' and name = 'Display Robô-Blocks serviço 3 unidade de cada.';
update public.products set name = 'ROBÔ-BLOCKS SERVIÇO VARREDOR - 46 PEÇAS' where code = '7172 - A' and name = 'ROBÔ-BLOCKS SERVIÇO VARREDOR - 46 PEÇAS 6 displays (18 unidades) +3 anos';
update public.products set name = 'ROBÔ-BLOCKS SERVIÇO DELIVERY - 45 PEÇAS' where code = '7173 - B' and name = 'ROBÔ-BLOCKS SERVIÇO DELIVERY - 45 PEÇAS 6 displays (18 unidades) +3 anos';
update public.products set name = 'ROBÔ-BLOCKS SERVIÇO CAMINHÃO PIPA - 45 PEÇAS' where code = '7174 - C' and name = 'ROBÔ-BLOCKS SERVIÇO CAMINHÃO PIPA - 45 PEÇAS 6 displays (18 unidades) +3 anos';
update public.products set name = 'ROBÔ-BLOCKS SERVIÇO AMBULÂNCIA - 47 PEÇAS' where code = '7175 - D' and name = 'ROBÔ-BLOCKS SERVIÇO AMBULÂNCIA - 47 PEÇAS 6 displays (18 unidades) +3 anos';
update public.products set name = 'Display Robô-Blocks Corrida' where code = '7176' and name = 'Display Robô-Blocks corrida 3 unidade de cada.';
update public.products set name = 'ROBÔ-BLOCKS CORRIDA F-CAR - 53 PEÇAS' where code = '7177 - A' and name = 'ROBÔ-BLOCKS CORRIDA F-CAR - 53 PEÇAS 6 displays (18 unidades) +3 anos';
update public.products set name = 'ROBÔ-BLOCKS CORRIDA F-ROAD - 59 PEÇAS' where code = '7178 - B' and name = 'ROBÔ-BLOCKS CORRIDA F-ROAD - 59 PEÇAS 6 displays (18 unidades) +3 anos';
update public.products set name = 'ROBÔ-BLOCKS CORRIDA F-QUADRI - 42 PEÇAS' where code = '7179 - C' and name = 'ROBÔ-BLOCKS CORRIDA F-QUADRI - 42 PEÇAS 6 displays (18 unidades) +3 anos';
update public.products set name = 'ROBÔ-BLOCKS CORRIDA F-RUN - 65 PEÇAS' where code = '7180 - D' and name = 'ROBÔ-BLOCKS CORRIDA F-RUN - 65 PEÇAS 6 displays (18 unidades) +3 anos';
update public.products set name = 'JEEP RALLY' where code = '1046' and name = 'JEEP RALLY (NA EMBALAGEM)';
update public.products set name = 'JEEP RALLY' where code = '1036' and name = 'JEEP RALLY (NO FILME)';
update public.products set name = 'TANDY CAÇAMBA' where code = '0071' and name = 'TANDY CAÇAMBA (NA REDE)';
update public.products set name = 'TANDY TRACTOR' where code = '0072' and name = 'TANDY TRACTOR (NA REDE)';
update public.products set name = 'TANDY BOMBEIRO' where code = '0078' and name = 'TANDY BOMBEIRO (NA REDE)';
