-- Cardoso Marketing Hub — projeto "Conferência de Embalagens" (importado do Monday.com)
-- Roda uma vez no SQL Editor, depois de 0001..0015 já terem rodado.

alter table public.tasks add column product_id uuid references public.products (id) on delete set null;
create index on public.tasks (product_id);

insert into public.projects (id, brand_id, name, sub, status, priority, category, start_date, objective)
values (
  gen_random_uuid(),
  (select id from public.brands where key = 'cardoso'),
  'Conferência de Embalagens',
  'Acompanhamento do desenvolvimento e aprovação de embalagens (importado do Monday)',
  'active',
  'high',
  'Embalagens',
  '2026-03-16',
  'Acompanhar o desenvolvimento, correção e aprovação de embalagens de produtos, com status sincronizado automaticamente na Lista de Produtos.'
) returning id;

-- A migration acima usa "returning id" só pra você conferir; o insert das demandas abaixo busca o projeto pelo nome.

insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3045' limit 1), 'Ref. 3045 3046 - Totoka', 'revisao', 'low', '2026-04-22', '2026-05-27', 'Grupo original (Monday): Em Avaliação · Validar até: 3 jun · Data de conclusão: 27 mai · Também relacionado aos códigos: 3046', 1);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3033' limit 1), 'Ref. 3033 3034 - Totokinha Bolinha', 'revisao', 'low', '2026-04-21', '2026-05-27', 'Grupo original (Monday): Em Avaliação · Validar até: 24 abr · Data de conclusão: 27 mai · Também relacionado aos códigos: 3034', 2);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '1044' limit 1), 'REF. 1044 - Invictus Graneleiro', 'revisao', 'high', '2026-04-01', null, 'Grupo original (Monday): Em Avaliação', 3);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7191' limit 1), 'Ref. 7191 - Patinete Azul decorado', 'revisao', 'low', '2026-04-23', '2026-05-29', 'Grupo original (Monday): Em Avaliação · Validar até: 29 abr · Data de conclusão: 29 mai', 4);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7192' limit 1), 'Ref. 7192 - Patinete Rosa decorado', 'revisao', 'low', '2026-04-23', '2026-05-29', 'Grupo original (Monday): Em Avaliação · Validar até: 29 abr · Data de conclusão: 29 mai', 5);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'REF. 7244 - Doce Cozinha Plus Frutinhas para cortar - Feirinha', 'revisao', 'medium', '2026-04-01', '2026-07-23', 'Grupo original (Monday): Em Avaliação · Validar até: 27 jul · Data de conclusão: 25 jul · Códigos sem produto cadastrado ainda: 7244', 6);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'REF. 7245 - Doce Cozinha Plus Frutinhas para cortar - Pomar', 'revisao', 'medium', '2026-04-01', '2026-07-23', 'Grupo original (Monday): Em Avaliação · Validar até: 27 jul · Data de conclusão: 25 jul · Códigos sem produto cadastrado ainda: 7245', 7);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'Ref. 7235 - Mesa Multiatividades com Tobogã com sons e luzes', 'recebido', 'medium', '2026-04-01', '2026-07-29', 'Grupo original (Monday): Produtos Importados - China · Data de conclusão: 29 jul · Códigos sem produto cadastrado ainda: 7235', 1);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'Ref. 7236 - Elefante Didático Multiesportivo Interativo com sons', 'recebido', 'medium', '2026-04-01', '2026-07-29', 'Grupo original (Monday): Produtos Importados - China · Data de conclusão: 29 jul · Códigos sem produto cadastrado ainda: 7236', 2);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'Ref. 7237 - Painel de Atividades Sensoriais com sons e luzes', 'recebido', 'medium', '2026-04-01', '2026-08-03', 'Grupo original (Monday): Produtos Importados - China · Data de conclusão: 3 ago · Códigos sem produto cadastrado ainda: 7237', 3);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'Ref. 7238 - Monta & Modela - Construção Criativa com 71 peças', 'recebido', 'medium', '2026-04-01', '2026-08-05', 'Grupo original (Monday): Produtos Importados - China · Data de conclusão: 5 ago · Códigos sem produto cadastrado ainda: 7238', 4);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'Ref. 7239 - Monta & Modela - Estação de Bombeiros com 66 peças', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Produtos Importados - China · Códigos sem produto cadastrado ainda: 7239', 5);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'Ref. 7240 - Monta & Modela - Castelo Encantado com 58 peças', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Produtos Importados - China · Códigos sem produto cadastrado ainda: 7240', 6);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'Ref. 7241 - Monta & Modela - Fazendinha Divertida com 48 peças', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Produtos Importados - China · Códigos sem produto cadastrado ainda: 7241', 7);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'Ref. 7242 - Monta & Modela - Hortinha Divertida com 50 peças', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Produtos Importados - China · Códigos sem produto cadastrado ainda: 7242', 8);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'Ref. 7243 - Monta & Modela - Parquinho Divertido com 46 peças', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Produtos Importados - China · Códigos sem produto cadastrado ainda: 7243', 9);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'Ref. 7234 - Cores a definir', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Produtos Importados - China · Códigos sem produto cadastrado ainda: 7234', 10);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'REF. NOME (copy)', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Produtos Importados - China', 11);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3085' limit 1), 'Ref. 3085 - Fofilhotes Ônibus com carretinha', 'finalizado', 'medium', '2026-03-24', '2026-05-08', 'Grupo original (Monday): Aprovados · Validar até: 5 mai · Data de conclusão: 29 abr', 1);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '1061' limit 1), 'Ref. 1061 - Open Tracks Trator Carregadeira', 'finalizado', 'high', '2026-03-16', '2026-05-14', 'Grupo original (Monday): Aprovados · Validar até: 14 mai · Data de conclusão: 12 mai', 2);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '1060' limit 1), 'Ref. 1060 - Open Tracks Trator Escavadeira', 'finalizado', 'high', '2026-03-16', '2026-05-14', 'Grupo original (Monday): Aprovados · Validar até: 14 mai · Data de conclusão: 12 mai', 3);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '1018' limit 1), 'Ref. 1018 - Combo 2 Construction', 'finalizado', 'medium', '2026-03-23', '2026-05-15', 'Grupo original (Monday): Aprovados · Validar até: 20 mai · Data de conclusão: 17 mai', 4);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3029' limit 1), 'Ref. 3029 - Dino Sabidinho Plus', 'finalizado', 'low', '2026-03-18', '2026-05-19', 'Grupo original (Monday): Aprovados · Validar até: 16 abr · Data de conclusão: 13 abr', 5);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3027' limit 1), 'Ref. 3027 - Dino Bombeirinho', 'finalizado', 'low', '2026-03-18', '2026-05-19', 'Grupo original (Monday): Aprovados · Validar até: 21 mai · Data de conclusão: 18 mai', 6);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2012' limit 1), 'Ref. 2012 - Geladeira Sonho de Menina', 'finalizado', 'medium', '2026-03-23', '2026-05-21', 'Grupo original (Monday): Aprovados · Validar até: 17 abr · Data de conclusão: 14 abr', 7);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4024' limit 1), 'Ref. 4024 - Trator Agro', 'finalizado', 'urgent', '2026-03-18', '2026-03-20', 'Grupo original (Monday): Aprovados · Validar até: 19 mar · Data de conclusão: 20 mar', 8);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4032' limit 1), 'Ref. 4032 - Bolopotamo com Números', 'finalizado', 'urgent', '2026-03-17', '2026-03-20', 'Grupo original (Monday): Aprovados · Validar até: 19 mar · Data de conclusão: 20 mar', 9);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4031' limit 1), 'Ref. 4031 - Bololéo com Letras', 'finalizado', 'urgent', '2026-03-17', '2026-03-20', 'Grupo original (Monday): Aprovados · Validar até: 19 mar · Data de conclusão: 20 mar', 10);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3058' limit 1), 'Ref. 3058 - Escolar', 'finalizado', 'urgent', '2026-03-17', '2026-03-20', 'Grupo original (Monday): Aprovados · Validar até: 19 mar · Data de conclusão: 20 mar', 11);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4010' limit 1), 'Ref. 4010 - Tamborete', 'finalizado', 'urgent', '2026-03-18', '2026-03-20', 'Grupo original (Monday): Aprovados · Validar até: 19 mar · Data de conclusão: 20 mar', 12);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4014' limit 1), 'Ref. 4014 - Tartaruga', 'finalizado', 'urgent', '2026-03-18', '2026-03-20', 'Grupo original (Monday): Aprovados · Validar até: 19 mar · Data de conclusão: 20 mar', 13);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4022' limit 1), 'Ref. 4022 - Trator Escavadeira', 'finalizado', 'urgent', '2026-03-18', '2026-03-20', 'Grupo original (Monday): Aprovados · Validar até: 19 mar · Data de conclusão: 20 mar', 14);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4023' limit 1), 'Ref. 4023 - Trator Retroescavadeira', 'finalizado', 'urgent', '2026-03-18', '2026-03-20', 'Grupo original (Monday): Aprovados · Validar até: 19 mar · Data de conclusão: 20 mar', 15);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4030' limit 1), 'Ref. 4030 - Bolofante com Formas Geométricas', 'finalizado', 'urgent', '2026-03-17', '2026-03-20', 'Grupo original (Monday): Aprovados · Validar até: 19 mar · Data de conclusão: 20 mar', 16);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3059' limit 1), 'Ref. 3059 - Sabidinho Plus', 'finalizado', 'urgent', '2026-03-17', '2026-03-20', 'Grupo original (Monday): Aprovados · Validar até: 19 mar · Data de conclusão: 20 mar', 17);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4028' limit 1), 'Ref. 4028 - Combo 2 Construction', 'finalizado', 'urgent', '2026-03-17', '2026-03-20', 'Grupo original (Monday): Aprovados · Validar até: 19 mar · Data de conclusão: 20 mar', 18);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3057' limit 1), 'Ref. 3057 - Bombeirinho', 'finalizado', 'urgent', '2026-03-17', '2026-03-20', 'Grupo original (Monday): Aprovados · Validar até: 19 mar · Data de conclusão: 20 mar', 19);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '0205' limit 1), 'Ref. 0205 - Baldão - Solapa', 'finalizado', 'medium', '2026-03-23', '2026-03-26', 'Grupo original (Monday): Aprovados · Validar até: 26 mar', 20);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2024' limit 1), 'Ref. 2024 - Doce Cozinha Gourmet Microondas', 'finalizado', 'urgent', '2026-03-24', '2026-04-15', 'Grupo original (Monday): Aprovados · Validar até: 20 abr · Data de conclusão: 15 abr', 21);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2022' limit 1), 'Ref. 2022 - Doce Cozinha Gourmet Liquidificador', 'finalizado', 'urgent', '2026-03-24', '2026-04-15', 'Grupo original (Monday): Aprovados · Validar até: 20 abr · Data de conclusão: 15 abr', 22);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2021' limit 1), 'Ref. 2021 - Doce Cozinha Gourmet Batedeira', 'finalizado', 'urgent', '2026-03-24', '2026-04-15', 'Grupo original (Monday): Aprovados · Validar até: 20 abr · Data de conclusão: 15 abr', 23);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2020' limit 1), 'Ref. 2020 - Doce Cozinha Gourmet Air Fryer', 'finalizado', 'urgent', '2026-03-24', '2026-04-15', 'Grupo original (Monday): Aprovados · Validar até: 20 abr · Data de conclusão: 15 abr', 24);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '1052' limit 1), 'Ref. 1052 - Dino - Solapa', 'finalizado', 'medium', '2026-03-23', '2026-04-13', 'Grupo original (Monday): Aprovados · Validar até: 16 abr · Data de conclusão: 13 abr', 25);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3090' limit 1), 'Ref. 3090 3091 3092 3093 3094 3095 - Fofilhotes', 'finalizado', 'medium', '2026-03-26', '2026-04-13', 'Grupo original (Monday): Aprovados · Validar até: 16 abr · Data de conclusão: 13 abr · Também relacionado aos códigos: 3091, 3092, 3093, 3094, 3095', 26);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3082' limit 1), 'Ref. 3082 - Fofilhotes Trenzinho', 'finalizado', 'medium', '2026-03-24', '2026-04-13', 'Grupo original (Monday): Aprovados · Validar até: 16 abr · Data de conclusão: 13 abr', 27);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3086' limit 1), 'Ref. 3086 - Fofilhotes Jipinho', 'finalizado', 'medium', '2026-03-24', '2026-04-27', 'Grupo original (Monday): Aprovados · Validar até: 30 abr · Data de conclusão: 27 abr', 28);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3084' limit 1), 'Ref. 3084 - Fofilhotes Ônibus', 'finalizado', 'medium', '2026-03-24', '2026-04-27', 'Grupo original (Monday): Aprovados · Validar até: 30 abr · Data de conclusão: 27 abr', 29);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3087' limit 1), 'Ref. 3087 - Fofilhotes Jipinho com Carretinha', 'finalizado', 'medium', '2026-03-24', '2026-04-27', 'Grupo original (Monday): Aprovados · Validar até: 30 abr · Data de conclusão: 27 abr', 30);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3083' limit 1), 'Ref. 3083 - Fofilhotes Trenzinho com Carretinha', 'finalizado', 'medium', '2026-03-24', '2026-04-27', 'Grupo original (Monday): Aprovados · Validar até: 30 abr · Data de conclusão: 27 abr', 31);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3088' limit 1), 'Ref. 3088 - Fofilhotes Tratorzinho', 'finalizado', 'medium', '2026-03-24', '2026-04-13', 'Grupo original (Monday): Aprovados · Validar até: 16 abr · Data de conclusão: 13 abr', 32);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3089' limit 1), 'Ref. 3089 - Fofilhotes Tratorzinho com Carretinha', 'finalizado', 'medium', '2026-03-24', '2026-04-27', 'Grupo original (Monday): Aprovados · Validar até: 30 abr · Data de conclusão: 27 abr', 33);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'REF. Caixa individual Totokinha Personagens', 'recebido', 'urgent', '2026-04-01', null, 'Grupo original (Monday): Aprovados', 1);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2023' limit 1), 'Ref. 2023 - Doce Cozinha Gourmet Máquina de Café Espresso', 'recebido', 'urgent', '2026-03-24', '2026-03-27', 'Grupo original (Monday): Aprovados · Validar até: 27 mar', 2);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3028' limit 1), 'Ref. 3028 - Dino Escolar', 'finalizado', 'low', '2026-03-18', '2026-05-19', 'Grupo original (Monday): Aprovados · Validar até: 21 mai · Data de conclusão: 19 mai', 34);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2017' limit 1), 'REF. 2017 - Geladeira Gela Sorvetinho', 'finalizado', 'low', '2026-03-19', '2026-05-21', 'Grupo original (Monday): Aprovados · Validar até: 26 mai · Data de conclusão: 22 mai', 35);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'Revisão SELO INMETRO das embalagens e solapas já fechadas', 'finalizado', 'medium', null, '2026-06-04', 'Grupo original (Monday): Aprovados · Data de conclusão: 4 jun', 36);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2014' limit 1), 'Ref. 2014 - Geladeira Gela Sorvetinho', 'finalizado', 'medium', '2026-03-23', '2026-05-21', 'Grupo original (Monday): Aprovados · Validar até: 26 mai · Data de conclusão: 22 mai', 37);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4009' limit 1), 'Ref. 4009 - Tópi Tambor', 'finalizado', 'urgent', null, '2026-05-25', 'Grupo original (Monday): Aprovados · Validar até: 25 mai · Data de conclusão: 26 mai', 38);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2019' limit 1), 'Ref. 2019 - Acqua Bubble - Caixa Individual', 'finalizado', 'medium', '2026-03-23', '2026-05-22', 'Grupo original (Monday): Aprovados · Validar até: 26 mai · Data de conclusão: 25 mai', 39);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2018' limit 1), 'Ref. 2018 - Acqua Bubble', 'recebido', 'medium', '2026-04-16', '2026-05-22', 'Grupo original (Monday): Aprovados · Validar até: 28 abr · Data de conclusão: 27 mai', 3);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3053' limit 1), 'Ref. 3053 3054 - Mesinha Atividades - Caixa Individual', 'finalizado', 'medium', '2026-03-25', '2026-05-25', 'Grupo original (Monday): Aprovados · Validar até: 28 mai · Data de conclusão: 13 abr · Também relacionado aos códigos: 3054', 40);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '3066' limit 1), 'Ref. 3066 3067 - Totokinha Sport', 'revisao', 'low', '2026-04-19', '2026-05-27', 'Grupo original (Monday): Aprovados · Validar até: 24 abr · Data de conclusão: 27 mai · Também relacionado aos códigos: 3067', 1);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '1059' limit 1), 'Ref. 1059 - Open Tracks Retroescavadeira - Playmi', 'finalizado', 'urgent', '2026-03-16', '2026-06-18', 'Grupo original (Monday): Aprovados · Validar até: 17 jun · Data de conclusão: 16 jun', 41);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '1062' limit 1), 'Ref. 1062 - Caminhão Air Truck Caçamba - Playmi', 'planejamento', 'urgent', '2026-03-25', '2026-06-18', 'Grupo original (Monday): Aprovados · Validar até: 17 jun · Data de conclusão: 16 jun', 1);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '1063' limit 1), 'Ref. 1063 - Caminhão Air Truck Escavadeira - Playmi', 'planejamento', 'urgent', '2026-03-25', '2026-06-18', 'Grupo original (Monday): Aprovados · Validar até: 17 jun · Data de conclusão: 16 jun', 2);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2013' limit 1), 'REF. 2013 - Cozinha Sonho de Menina - Playmi', 'finalizado', 'urgent', '2026-03-18', '2026-06-18', 'Grupo original (Monday): Aprovados · Validar até: 22 jun · Data de conclusão: 16 jun', 42);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '1045' limit 1), 'REF. 1045 - Invictus Resgate - Tópi', 'finalizado', 'high', '2026-04-01', '2026-06-23', 'Grupo original (Monday): Aprovados · Validar até: 24 jun · Data de conclusão: 23 jun', 43);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '1042' limit 1), 'Ref. 1042 - Invictus Basculante - Tópi', 'finalizado', 'high', null, null, 'Grupo original (Monday): Aprovados', 44);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '1046' limit 1), 'Ref. 1046 - Jeep Rally - Tópi', 'finalizado', 'medium', '2026-04-01', '2026-06-23', 'Grupo original (Monday): Aprovados · Validar até: 24 jun · Data de conclusão: 23 jun', 45);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2003' limit 1), 'Ref. 2003 2009 - Carrinho de Boneca - Tópi', 'finalizado', 'high', '2026-03-31', '2026-05-05', 'Grupo original (Monday): Aprovados · Validar até: 11 mai · Data de conclusão: 5 mai · Também relacionado aos códigos: 2009', 46);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2004' limit 1), 'Ref. 2004 - Doce Cozinha Almocinho - Tópi', 'finalizado', 'urgent', '2026-05-03', '2026-05-08', 'Grupo original (Monday): Aprovados · Validar até: 8 mai · Data de conclusão: 5 mai', 47);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2005' limit 1), 'Ref. 2005 - Doce Cozinha Lanchinho - Tópi', 'finalizado', 'urgent', '2026-05-03', '2026-05-08', 'Grupo original (Monday): Aprovados · Validar até: 8 mai · Data de conclusão: 5 mai', 48);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2006' limit 1), 'Ref. 2006 - Doce Cozinha Jantinha (Laço Roxo) - Tópi', 'finalizado', 'urgent', '2026-05-03', '2026-05-08', 'Grupo original (Monday): Aprovados · Validar até: 8 mai · Data de conclusão: 5 mai', 49);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2011' limit 1), 'Ref. 2011 - Doce Cozinha Fogãozinho - Tópi', 'finalizado', 'urgent', '2026-05-03', '2026-05-08', 'Grupo original (Monday): Aprovados · Validar até: 8 mai · Data de conclusão: 5 mai', 50);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2010' limit 1), 'Ref. 2010 - Doce Cozinha Faz de Conta - Tópi', 'finalizado', 'urgent', '2026-05-03', '2026-05-08', 'Grupo original (Monday): Aprovados · Validar até: 8 mai · Data de conclusão: 5 mai', 51);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '8015' limit 1), 'Ref. 8015 - Trenzinho Didático 28 pçs - Playmi', 'finalizado', 'urgent', '2026-04-05', '2026-05-15', 'Grupo original (Monday): Aprovados · Validar até: 16 abr · Data de conclusão: 13 abr', 52);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '8011' limit 1), 'Ref. 8011 - Block Box Menina - Playmi', 'finalizado', 'urgent', '2026-04-05', '2026-05-15', 'Grupo original (Monday): Aprovados · Validar até: 26 mai · Data de conclusão: 23 mai', 53);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '8012' limit 1), 'Ref. 8012 - Block Box Menino - Playmi', 'finalizado', 'urgent', '2026-04-05', '2026-05-15', 'Grupo original (Monday): Aprovados · Validar até: 26 mai · Data de conclusão: 23 mai', 54);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '9047' limit 1), 'Ref. 9047 - Comboio Rodeio - Tópi', 'finalizado', 'medium', '2026-04-01', '2026-06-26', 'Grupo original (Monday): Aprovados · Validar até: 25 jun · Data de conclusão: 24 jun', 55);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '0280' limit 1), 'Ref. 0280 - Mipuxa - Tópi', 'finalizado', 'medium', '2026-04-01', '2026-06-26', 'Grupo original (Monday): Aprovados · Validar até: 25 jun · Data de conclusão: 24 jun', 56);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '1007' limit 1), 'REF. 1007 - Dino Sabidinho - Tópi', 'finalizado', 'high', '2026-04-01', '2026-06-26', 'Grupo original (Monday): Aprovados · Validar até: 25 jun · Data de conclusão: 24 jun', 57);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7107' limit 1), 'REF. 7107 - Polvo Musical Azul', 'finalizado', 'medium', '2026-04-01', '2026-07-03', 'Grupo original (Monday): Aprovados · Validar até: 8 jul · Data de conclusão: 7 jul', 58);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7159' limit 1), 'REF. 7159 - Bateria Musical Azul', 'finalizado', 'medium', '2026-04-01', '2026-07-03', 'Grupo original (Monday): Aprovados · Validar até: 8 jul · Data de conclusão: 7 jul', 59);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7195' limit 1), 'REF. 7195 - Dino Vrum Vrum Didático', 'finalizado', 'medium', '2026-04-01', '2026-07-03', 'Grupo original (Monday): Aprovados · Validar até: 10 jul · Data de conclusão: 9 jul', 60);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7201' limit 1), 'REF. 7201 - Mesinha Musical Carrossel dos Bichinhos Azul', 'finalizado', 'medium', '2026-04-01', '2026-07-03', 'Grupo original (Monday): Aprovados · Validar até: 8 jul · Data de conclusão: 7 jul', 61);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7202' limit 1), 'REF. 7202 - Mesinha Musical Carrossel dos Bichinhos Rosa', 'finalizado', 'high', '2026-04-01', '2026-07-03', 'Grupo original (Monday): Aprovados · Validar até: 13 jul', 62);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7181' limit 1), 'REF. 7181 - Doce Cozinha Plus Brincando de Cozinhar', 'finalizado', 'high', '2026-04-01', '2026-07-15', 'Grupo original (Monday): Aprovados · Validar até: 17 jul · Data de conclusão: 16 jul', 63);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7183' limit 1), 'REF. 7183 - Doce Cozinha Plus Sandwich', 'finalizado', 'high', '2026-04-01', '2026-07-15', 'Grupo original (Monday): Aprovados · Validar até: 17 jul · Data de conclusão: 16 jul', 64);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7182' limit 1), 'REF. 7182 - Doce Cozinha Plus Grill', 'finalizado', 'high', '2026-04-01', '2026-07-15', 'Grupo original (Monday): Aprovados · Validar até: 15 jul · Data de conclusão: 14 jul', 65);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7122' limit 1), 'REF. 7122 - Doce Cozinha Plus Comidinha', 'finalizado', 'high', '2026-04-01', '2026-07-15', 'Grupo original (Monday): Aprovados · Validar até: 16 jul · Data de conclusão: 15 jul', 66);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7123' limit 1), 'REF. 7123 - Doce Cozinha Plus Liquidificador', 'finalizado', 'high', '2026-04-01', '2026-07-15', 'Grupo original (Monday): Aprovados · Validar até: 16 jul · Data de conclusão: 15 jul', 67);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7124' limit 1), 'REF. 7124 - Doce Cozinha Plus Microondas e Batedeira', 'finalizado', 'high', '2026-04-01', '2026-07-15', 'Grupo original (Monday): Aprovados · Validar até: 17 jul · Data de conclusão: 16 jul', 68);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7125' limit 1), 'REF. 7125 - Doce Cozinha Plus Torradeira e Batedeira', 'finalizado', 'high', '2026-04-01', '2026-07-15', 'Grupo original (Monday): Aprovados · Validar até: 15 jul · Data de conclusão: 14 jul', 69);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7161' limit 1), 'REF. 7161 - Fire Rescue Bombeiro', 'finalizado', 'medium', '2026-04-01', '2026-07-17', 'Grupo original (Monday): Aprovados · Validar até: 23 jul · Data de conclusão: 22 jul', 70);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '7162' limit 1), 'REF. 7162 - Fire Rescue Polícia', 'finalizado', 'medium', '2026-04-01', '2026-07-17', 'Grupo original (Monday): Aprovados · Validar até: 23 jul · Data de conclusão: 22 jul', 71);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'REF. NOME', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Pendentes', 1);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '2016' limit 1), 'Ref. 2016 - Cozinha Sonho de Menina - Caixa Individual', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Pendentes', 2);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4018' limit 1), 'Ref. 4018 - Tópi Invictus Caçamba - Solapa', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Pendentes', 3);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4025' limit 1), 'Ref. 4025 - Tópi Invictus Graneleiro - Solapa', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Pendentes', 4);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4029' limit 1), 'Ref. 4029 - Tópi Invictus Super Cegonheiro - Solapa', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Pendentes', 5);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4026' limit 1), 'Ref. 4026 - Tópi Cestinha Didática - Solapa', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Pendentes', 6);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'Ref. 4011 - Tópi Guitarra - Solapa', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Pendentes · Códigos sem produto cadastrado ainda: 4011', 7);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), null, 'Ref. 4011 - Tópi Pandeiro - Solapa', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Pendentes · Códigos sem produto cadastrado ainda: 4011', 8);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4013' limit 1), 'Ref. 4013 - Tópi Dino Sabidinho - Solapa', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Pendentes', 9);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4015' limit 1), 'Ref. 4015 - Tópi Pata Bota Ovo - Solapa', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Pendentes', 10);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4016' limit 1), 'Ref. 4016 - Tópi Mileva - Solapa', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Pendentes', 11);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4019' limit 1), 'Ref. 4019 - Tópi Batedeira - Solapa', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Pendentes', 12);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4020' limit 1), 'Ref. 4020 - Tópi Liquidificador - Solapa', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Pendentes', 13);
insert into public.tasks (project_id, product_id, title, stage, priority, start_date, due_date, notes, position) values ((select id from public.projects where name = 'Conferência de Embalagens' order by created_at desc limit 1), (select id from public.products where code = '4021' limit 1), 'Ref. 4021 - Tópi Fogãozinho - Solapa', 'recebido', 'medium', '2026-04-01', null, 'Grupo original (Monday): Pendentes', 14);
