-- Cardoso Marketing Hub — atualização de dados a partir da FICHA TÉCNICA (2026)
-- Parte 4 de 11 — rode cada parte separadamente no SQL Editor, uma de cada vez, nessa ordem.
-- (O arquivo original era grande demais e o colar no SQL Editor estava sendo cortado no meio, sem erro visível.)
-- Depois de rodar TODAS as partes, confira: select code, name, gender, material, toy_category, ean from products where code = '0280';

update public.products set
  name = 'TOTOKA PLUS SEM ELETRÔNICO AZUL CAIXA INDIVIDUAL',
  line = 'PLAY&RIDE',
  technical_name = null,
  ean = '789648416008-7',
  age_range = '+ 18 meses',
  gender = 'Menino',
  material = 'Plástico',
  color = 'Azul',
  product_length_mm = 495,
  product_width_mm = 250,
  product_height_mm = 348,
  product_volume_m3 = 0.043065,
  product_weight_kg = 2.035,
  has_mechanism = true,
  has_sound = true,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = '40kg',
  toy_category = 'Primeiros Passos',
  package_contents = '1 Totoka 
1 haste para empurrar
1 apoio de braço
1 par de apoio para os pés',
  package_length_mm = 510,
  package_width_mm = 310,
  package_height_mm = 380,
  package_volume_m3 = 0.060078,
  package_weight_kg = 2.49,
  ncm = '9503.00.10',
  cst = '500',
  dun = 'X',
  carton_length_mm = 510,
  carton_width_mm = 310,
  carton_height_mm = 385,
  carton_volume_m3 = 0.0609,
  carton_quantity = 1,
  carton_gross_weight_kg = 2.49,
  pallet_layer_pattern = '5X4',
  pallet_height_m = 1.35,
  pallet_total_units = 20
where code = '6008';

update public.products set
  name = 'TOTOKA PLUS BABY TRACTOR CAIXA  INDIVIDUAL',
  line = 'PLAY&RIDE',
  technical_name = null,
  ean = '789648416009-4',
  age_range = '+ 18 meses',
  gender = 'Unissex',
  material = 'Plástico',
  color = 'Amarelo',
  product_length_mm = 495,
  product_width_mm = 250,
  product_height_mm = 348,
  product_volume_m3 = 0.043065,
  product_weight_kg = 2.035,
  has_mechanism = true,
  has_sound = true,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = '40kg',
  toy_category = 'Primeiros Passos',
  package_contents = '1 Totoka 
1 haste para empurrar
1 apoio de braço
1 par de apoio para os pés',
  package_length_mm = 326,
  package_width_mm = 508,
  package_height_mm = 303,
  package_volume_m3 = 0.050179224,
  package_weight_kg = 2.49,
  ncm = '9503.00.10',
  cst = '500',
  dun = 'X',
  carton_length_mm = 510,
  carton_width_mm = 310,
  carton_height_mm = 385,
  carton_volume_m3 = 0.0609,
  carton_quantity = 1,
  carton_gross_weight_kg = 2.49,
  pallet_layer_pattern = '5X4',
  pallet_height_m = 1.35,
  pallet_total_units = 20
where code = '6009';

update public.products set
  name = 'TOTOKINHA SPORT ROSA CAIXA INDIVIDUAL',
  line = 'PLAY&RIDE',
  technical_name = null,
  ean = '789648416010-0',
  age_range = '+ 18 meses',
  gender = 'Menina',
  material = 'Plástico',
  color = 'Rosa',
  product_length_mm = 498,
  product_width_mm = 283,
  product_height_mm = 316,
  product_volume_m3 = 0.044535144,
  product_weight_kg = 1.24,
  has_mechanism = true,
  has_sound = true,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = '40kg',
  toy_category = 'Primeiros Passos',
  package_contents = '1 Totokinha Sport
4 formas geométricas',
  package_length_mm = 326,
  package_width_mm = 508,
  package_height_mm = 303,
  package_volume_m3 = 0.050179224,
  package_weight_kg = 2.14,
  ncm = '9503.00.10',
  cst = '000',
  dun = 'X',
  carton_length_mm = 510,
  carton_width_mm = 290,
  carton_height_mm = 330,
  carton_volume_m3 = 0.0488,
  carton_quantity = 1,
  carton_gross_weight_kg = 1.76,
  pallet_layer_pattern = '8X4',
  pallet_height_m = 1.47,
  pallet_total_units = 32
where code = '6010';

update public.products set
  name = 'TOTOKINHA SPORT AZUL CAIXA INDIVIDUAL',
  line = 'PLAY&RIDE',
  technical_name = null,
  ean = '789648416011-7',
  age_range = '+ 18 meses',
  gender = 'Menino',
  material = 'Plástico',
  color = 'Azul',
  product_length_mm = 498,
  product_width_mm = 283,
  product_height_mm = 316,
  product_volume_m3 = 0.044535144,
  product_weight_kg = 1.24,
  has_mechanism = true,
  has_sound = true,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = '40kg',
  toy_category = 'Primeiros Passos',
  package_contents = '1 Totokinha Sport
4 formas geométricas',
  package_length_mm = 326,
  package_width_mm = 508,
  package_height_mm = 303,
  package_volume_m3 = 0.050179224,
  package_weight_kg = 2.14,
  ncm = '9503.00.10',
  cst = '000',
  dun = 'X',
  carton_length_mm = 510,
  carton_width_mm = 290,
  carton_height_mm = 330,
  carton_volume_m3 = 0.0488,
  carton_quantity = 1,
  carton_gross_weight_kg = 1.76,
  pallet_layer_pattern = '8X4',
  pallet_height_m = 1.47,
  pallet_total_units = 32
where code = '6011';

update public.products set
  name = 'PATINETE AZUL DECORADO',
  line = 'PLAY&RIDE',
  technical_name = null,
  ean = '789648417191-5',
  age_range = '+ 2 Anos',
  gender = 'MENINO',
  material = 'PLASTICO',
  color = 'AZUL',
  product_length_mm = 550,
  product_width_mm = 200,
  product_height_mm = 770,
  product_volume_m3 = 0.0847,
  product_weight_kg = 1.5,
  has_mechanism = true,
  has_sound = false,
  has_light = true,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Montaria',
  package_contents = '1 Patinete decorado com luzes',
  package_length_mm = 510,
  package_width_mm = 160,
  package_height_mm = 270,
  package_volume_m3 = 0.022032,
  package_weight_kg = 2.15,
  ncm = '9503.00.10',
  cst = null,
  dun = '2789648417191-9',
  carton_length_mm = 590,
  carton_width_mm = 430,
  carton_height_mm = 390,
  carton_volume_m3 = 0.098943,
  carton_quantity = 6,
  carton_gross_weight_kg = 11.34,
  pallet_layer_pattern = '4x4',
  pallet_height_m = 1.65,
  pallet_total_units = 16
where code = '7191';

update public.products set
  name = 'PATINETE ROSA DECORADO',
  line = 'PLAY&RIDE',
  technical_name = null,
  ean = '789648417192-2',
  age_range = '+ 2 Anos',
  gender = 'MENINA',
  material = 'PLASTICO',
  color = 'ROSA',
  product_length_mm = 550,
  product_width_mm = 200,
  product_height_mm = 770,
  product_volume_m3 = 0.0847,
  product_weight_kg = 1.5,
  has_mechanism = true,
  has_sound = false,
  has_light = true,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Montaria',
  package_contents = '1 Patinete decorado com luzes',
  package_length_mm = 510,
  package_width_mm = 160,
  package_height_mm = 270,
  package_volume_m3 = 0.022032,
  package_weight_kg = 2.15,
  ncm = '9503.00.10',
  cst = null,
  dun = '2789648417192-6',
  carton_length_mm = 590,
  carton_width_mm = 430,
  carton_height_mm = 390,
  carton_volume_m3 = 0.098943,
  carton_quantity = 6,
  carton_gross_weight_kg = 11.34,
  pallet_layer_pattern = '4x4',
  pallet_height_m = 1.65,
  pallet_total_units = 16
where code = '7192';

update public.products set
  name = 'GELADEIRA SONHO DE MENINA',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648412012-8',
  age_range = '+ 3 Anos',
  gender = 'Menina',
  material = 'Plástico',
  color = 'Rosa',
  product_length_mm = 255,
  product_width_mm = 202,
  product_height_mm = 486,
  product_volume_m3 = 0.02503386,
  product_weight_kg = 1.775,
  has_mechanism = false,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '1 Geladeira Sonho de Menina
2 prateleiras
1 porta ovos
1  forma de picolé com 4 
4 ovos
1 cartela de adesivos',
  package_length_mm = 315,
  package_width_mm = 230,
  package_height_mm = 500,
  package_volume_m3 = 0.036225,
  package_weight_kg = 1.42,
  ncm = '9503.00.80',
  cst = '000',
  dun = '9789648412012-1',
  carton_length_mm = 310,
  carton_width_mm = 420,
  carton_height_mm = 530,
  carton_volume_m3 = 0.069,
  carton_quantity = 2,
  carton_gross_weight_kg = 3.38,
  pallet_layer_pattern = '5X4',
  pallet_height_m = 1.44,
  pallet_total_units = 20
where code = '2012';

update public.products set
  name = 'COZINHA SONHO DE MENINA',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648412013-5',
  age_range = '+ 3 Anos',
  gender = 'Menina',
  material = 'Plástico',
  color = 'Rosa',
  product_length_mm = 266,
  product_width_mm = 206,
  product_height_mm = 486,
  product_volume_m3 = 0.032110456,
  product_weight_kg = 0.84,
  has_mechanism = false,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = 'A Cozinha Sonho de Menina vem com 1 panela com tampa, 2 pratos, 1 espátula, 1 concha,
1 escumadeira, 2 garfos, 2 facas e 2 colheres e cartões pop-up para recortar no verso da embalagem.',
  package_length_mm = 315,
  package_width_mm = 230,
  package_height_mm = 500,
  package_volume_m3 = 0.036225,
  package_weight_kg = 1.18,
  ncm = '9503.00.80',
  cst = '000',
  dun = '9789648412013-8',
  carton_length_mm = 310,
  carton_width_mm = 420,
  carton_height_mm = 530,
  carton_volume_m3 = 0.069,
  carton_quantity = 2,
  carton_gross_weight_kg = 2.96,
  pallet_layer_pattern = '5X4',
  pallet_height_m = 1.44,
  pallet_total_units = 20
where code = '2013';

update public.products set
  name = 'GELADEIRA GELA SORVETINHO',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648412014-2',
  age_range = '+ 3 Anos',
  gender = 'Menina',
  material = 'Plástico',
  color = 'Rosa',
  product_length_mm = 255,
  product_width_mm = 202,
  product_height_mm = 486,
  product_volume_m3 = 0.02503386,
  product_weight_kg = 1.775,
  has_mechanism = true,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = 'A Geladeira Gela Sorvetinho vem com 2 sorvetinhos, 2 casquinhas, 1 forminha para fazer
sorvete, 2 prateleiras internas, além do dispenser que sai sorvetinho.',
  package_length_mm = 340,
  package_width_mm = 210,
  package_height_mm = 500,
  package_volume_m3 = 0.0357,
  package_weight_kg = 1.7,
  ncm = '9503.00.80',
  cst = '000',
  dun = '9789648412014-5',
  carton_length_mm = 350,
  carton_width_mm = 440,
  carton_height_mm = 530,
  carton_volume_m3 = 0.08162,
  carton_quantity = 2,
  carton_gross_weight_kg = 3.92,
  pallet_layer_pattern = '8x2',
  pallet_height_m = 1.18,
  pallet_total_units = 16
where code = '2014';

update public.products set
  name = 'GELADEIRA SONHO DE MENINA CAIXA INDIVIDUAL',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648412015-9',
  age_range = '+ 3 Anos',
  gender = 'Menina',
  material = 'Plástico',
  color = 'Rosa',
  product_length_mm = 255,
  product_width_mm = 202,
  product_height_mm = 486,
  product_volume_m3 = 0.02503386,
  product_weight_kg = 1.775,
  has_mechanism = false,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '1 Geladeira Sonho de Menina
2 prateleiras
1 porta ovos
1  forma de picolé com 4 
4 ovos
1 cartela de adesivos',
  package_length_mm = 264,
  package_width_mm = 212,
  package_height_mm = 501,
  package_volume_m3 = 0.028039968,
  package_weight_kg = 1.42,
  ncm = '9503.00.80',
  cst = '000',
  dun = 'X',
  carton_length_mm = 220,
  carton_width_mm = 270,
  carton_height_mm = 500,
  carton_volume_m3 = 0.0297,
  carton_quantity = 1,
  carton_gross_weight_kg = 1.38,
  pallet_layer_pattern = '18x3',
  pallet_height_m = 1.65,
  pallet_total_units = 54
where code = '2015';

update public.products set
  name = 'COZINHA SONHO DE MENINA CAIXA INDIVIDUAL',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648412016-6',
  age_range = '+ 3 Anos',
  gender = 'Menina',
  material = 'Plástico',
  color = 'Rosa',
  product_length_mm = 266,
  product_width_mm = 206,
  product_height_mm = 486,
  product_volume_m3 = 0.032110456,
  product_weight_kg = 0.84,
  has_mechanism = false,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = 'A Cozinha Sonho de Menina vem com 1 panela com tampa, 2 pratos, 1 espátula, 1 concha,
1 escumadeira, 2 garfos, 2 facas e 2 colheres e cartões pop-up para recortar no verso da embalagem.',
  package_length_mm = 275,
  package_width_mm = 243,
  package_height_mm = 276,
  package_volume_m3 = 0.0184437,
  package_weight_kg = 1.18,
  ncm = '9503.00.80',
  cst = '000',
  dun = 'X',
  carton_length_mm = 250,
  carton_width_mm = 270,
  carton_height_mm = 300,
  carton_volume_m3 = 0.02025,
  carton_quantity = 1,
  carton_gross_weight_kg = 1.08,
  pallet_layer_pattern = '16X5',
  pallet_height_m = 1.6,
  pallet_total_units = 80
where code = '2016';

update public.products set
  name = 'GELADEIRA GELA SORVETINHO CAIXA INDIVIDUAL',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648412017-3',
  age_range = '+ 3 Anos',
  gender = 'Menina',
  material = 'Plástico',
  color = 'Rosa',
  product_length_mm = 255,
  product_width_mm = 202,
  product_height_mm = 486,
  product_volume_m3 = 0.02503386,
  product_weight_kg = 1.775,
  has_mechanism = true,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = 'A Geladeira Gela Sorvetinho vem com 2 sorvetinhos, 2 casquinhas, 1 forminha para fazer
sorvete, 2 prateleiras internas, além do dispenser que sai sorvetinho.',
  package_length_mm = 264,
  package_width_mm = 212,
  package_height_mm = 501,
  package_volume_m3 = 0.028039968,
  package_weight_kg = 1.7,
  ncm = '9503.00.80',
  cst = '000',
  dun = 'X',
  carton_length_mm = 220,
  carton_width_mm = 270,
  carton_height_mm = 500,
  carton_volume_m3 = 0.0297,
  carton_quantity = 1,
  carton_gross_weight_kg = 1.42,
  pallet_layer_pattern = '18x3',
  pallet_height_m = 1.65,
  pallet_total_units = 54
where code = '2017';

update public.products set
  name = 'ACQUA BUBBLE',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648412018-0',
  age_range = '+ 3 Anos',
  gender = 'Menina',
  material = 'Plástico',
  color = 'Rosa',
  product_length_mm = 307,
  product_width_mm = 190,
  product_height_mm = 500,
  product_volume_m3 = 0.0291,
  product_weight_kg = 1.19,
  has_mechanism = true,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '1 Acqua Bubble 
2 pratos
2 garfos
2 facas
2 colheres
1 concha
1 escumadeira
1 espatula',
  package_length_mm = 315,
  package_width_mm = 190,
  package_height_mm = 500,
  package_volume_m3 = 0.029925,
  package_weight_kg = 1.515,
  ncm = '9503.00.80',
  cst = '000',
  dun = '9789648412018-3',
  carton_length_mm = 325,
  carton_width_mm = 410,
  carton_height_mm = 530,
  carton_volume_m3 = 0.070623,
  carton_quantity = 2,
  carton_gross_weight_kg = 3.53,
  pallet_layer_pattern = '5x4',
  pallet_height_m = 1.44,
  pallet_total_units = 20
where code = '2018';

update public.products set
  name = 'ACQUA BUBBLE CAIXA INDIVIDUAL',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648412019-7',
  age_range = '+ 3 Anos',
  gender = 'Menina',
  material = 'Plástico',
  color = 'Rosa',
  product_length_mm = 307,
  product_width_mm = 190,
  product_height_mm = 500,
  product_volume_m3 = 0.0291,
  product_weight_kg = 1.19,
  has_mechanism = true,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '1 Acqua Bubble 
2 pratos
2 garfos
2 facas
2 colheres
1 concha
1 escumadeira
1 espatula',
  package_length_mm = 315,
  package_width_mm = 190,
  package_height_mm = 500,
  package_volume_m3 = 0.029925,
  package_weight_kg = 1.19,
  ncm = '9503.00.80',
  cst = '000',
  dun = 'X',
  carton_length_mm = 315,
  carton_width_mm = 200,
  carton_height_mm = 530,
  carton_volume_m3 = 0.03339,
  carton_quantity = 1,
  carton_gross_weight_kg = 1.52,
  pallet_layer_pattern = '18x2',
  pallet_height_m = 1.18,
  pallet_total_units = 36
where code = '2019';

update public.products set
  name = 'Doce Cozinha Gourmet Air Fryer',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648412020-3',
  age_range = '+ 3 Anos',
  gender = 'MENINA',
  material = 'PLASTICO',
  color = 'ROSA',
  product_length_mm = 187,
  product_width_mm = 229,
  product_height_mm = 221,
  product_volume_m3 = 0.009464,
  product_weight_kg = 0.215,
  has_mechanism = false,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '1 fritadeira Air Fryer com cesto',
  package_length_mm = null,
  package_width_mm = null,
  package_height_mm = null,
  package_volume_m3 = null,
  package_weight_kg = null,
  ncm = '9503.00.80',
  cst = null,
  dun = '2789648412020-7',
  carton_length_mm = null,
  carton_width_mm = null,
  carton_height_mm = null,
  carton_volume_m3 = null,
  carton_quantity = 6,
  carton_gross_weight_kg = null,
  pallet_layer_pattern = null,
  pallet_height_m = null,
  pallet_total_units = null
where code = '2020';

update public.products set
  name = 'Doce Cozinha Gourmet Batedeira',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648412021-0',
  age_range = '+ 3 Anos',
  gender = 'MENINA',
  material = 'PLASTICO',
  color = 'ROSA',
  product_length_mm = 196,
  product_width_mm = 122,
  product_height_mm = 249,
  product_volume_m3 = 0.005954,
  product_weight_kg = 0.27,
  has_mechanism = false,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '1 batedeira 
1 recipiente',
  package_length_mm = null,
  package_width_mm = null,
  package_height_mm = null,
  package_volume_m3 = null,
  package_weight_kg = null,
  ncm = '9503.00.80',
  cst = null,
  dun = '2789648412021-4',
  carton_length_mm = null,
  carton_width_mm = null,
  carton_height_mm = null,
  carton_volume_m3 = null,
  carton_quantity = 6,
  carton_gross_weight_kg = null,
  pallet_layer_pattern = null,
  pallet_height_m = null,
  pallet_total_units = null
where code = '2021';

update public.products set
  name = 'Doce Cozinha Gourmet Liquidificador',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648412022-7',
  age_range = '+ 3 Anos',
  gender = 'MENINA',
  material = 'PLASTICO',
  color = 'ROSA',
  product_length_mm = 158,
  product_width_mm = 130,
  product_height_mm = 268,
  product_volume_m3 = 0.005505,
  product_weight_kg = 0.27,
  has_mechanism = false,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '1 liquidificador com tampa',
  package_length_mm = null,
  package_width_mm = null,
  package_height_mm = null,
  package_volume_m3 = null,
  package_weight_kg = null,
  ncm = '9503.00.80',
  cst = null,
  dun = '2789648412022-1',
  carton_length_mm = null,
  carton_width_mm = null,
  carton_height_mm = null,
  carton_volume_m3 = null,
  carton_quantity = 6,
  carton_gross_weight_kg = null,
  pallet_layer_pattern = null,
  pallet_height_m = null,
  pallet_total_units = null
where code = '2022';

update public.products set
  name = 'Doce Cozinha Gourmet Máquina de Café Espresso',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648412023-4',
  age_range = '+ 3 Anos',
  gender = 'MENINA',
  material = 'PLASTICO',
  color = 'ROSA',
  product_length_mm = 140,
  product_width_mm = 230,
  product_height_mm = 210,
  product_volume_m3 = 0.006762,
  product_weight_kg = 0.27,
  has_mechanism = false,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '1 máquina de café espresso 
2 cápsulas
1 xícara',
  package_length_mm = null,
  package_width_mm = null,
  package_height_mm = null,
  package_volume_m3 = null,
  package_weight_kg = null,
  ncm = '9503.00.80',
  cst = null,
  dun = '2789648412023-8',
  carton_length_mm = null,
  carton_width_mm = null,
  carton_height_mm = null,
  carton_volume_m3 = null,
  carton_quantity = 6,
  carton_gross_weight_kg = null,
  pallet_layer_pattern = null,
  pallet_height_m = null,
  pallet_total_units = null
where code = '2023';

update public.products set
  name = 'Doce Cozinha Gourmet Microondas',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648412024-1',
  age_range = '+ 3 Anos',
  gender = 'MENINA',
  material = 'PLASTICO',
  color = 'ROSA',
  product_length_mm = 247,
  product_width_mm = 164,
  product_height_mm = 162,
  product_volume_m3 = 0.006562,
  product_weight_kg = 0.27,
  has_mechanism = false,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '1 microondas com prato giratório',
  package_length_mm = null,
  package_width_mm = null,
  package_height_mm = null,
  package_volume_m3 = null,
  package_weight_kg = null,
  ncm = '9503.00.80',
  cst = null,
  dun = '2789648412024-5',
  carton_length_mm = null,
  carton_width_mm = null,
  carton_height_mm = null,
  carton_volume_m3 = null,
  carton_quantity = 6,
  carton_gross_weight_kg = null,
  pallet_layer_pattern = null,
  pallet_height_m = null,
  pallet_total_units = null
where code = '2024';

update public.products set
  name = 'DOCE COZINHA PLUS COMIDINHA',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648417122-9',
  age_range = '+ 3 Anos',
  gender = 'Menina',
  material = 'Plástico',
  color = 'Rosa',
  product_length_mm = 410,
  product_width_mm = 85,
  product_height_mm = 305,
  product_volume_m3 = 0.01062925,
  product_weight_kg = 0.245,
  has_mechanism = true,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '1 pia com escorredor
1 tabua
3 facas
1 amolador
1 descascador
1 berinjela
1 repolho
1 tomate
1 cenoura',
  package_length_mm = 410,
  package_width_mm = 85,
  package_height_mm = 305,
  package_volume_m3 = 0.01062925,
  package_weight_kg = 0.54,
  ncm = '9503.00.80',
  cst = '000',
  dun = '2789648417122-3',
  carton_length_mm = 510,
  carton_width_mm = 420,
  carton_height_mm = 330,
  carton_volume_m3 = 0.070686,
  carton_quantity = 6,
  carton_gross_weight_kg = 3.936,
  pallet_layer_pattern = '5x4',
  pallet_height_m = 1.45,
  pallet_total_units = 20
where code = '7122';

update public.products set
  name = 'DOCE COZINHA PLUS LIQUIDIFICADOR',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648417123-6',
  age_range = '+ 3 Anos',
  gender = 'Menina',
  material = 'Plástico',
  color = 'Rosa',
  product_length_mm = 410,
  product_width_mm = 85,
  product_height_mm = 305,
  product_volume_m3 = 0.01062925,
  product_weight_kg = 0.201,
  has_mechanism = true,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '1 liquidificador
1 tabua
1 prato
1 suporte para facas
3 facas
1 amolador
1 descascador
1 maça
1 kiwi
1 carambola
1 pêra',
  package_length_mm = 410,
  package_width_mm = 85,
  package_height_mm = 305,
  package_volume_m3 = 0.01062925,
  package_weight_kg = 0.485,
  ncm = '9503.00.80',
  cst = '000',
  dun = '2789648417123-0',
  carton_length_mm = 510,
  carton_width_mm = 420,
  carton_height_mm = 330,
  carton_volume_m3 = 0.070686,
  carton_quantity = 6,
  carton_gross_weight_kg = 3.6,
  pallet_layer_pattern = '5x4',
  pallet_height_m = 1.45,
  pallet_total_units = 20
where code = '7123';

update public.products set
  name = 'DOCE COZINHA PLUS MICROONDAS E BATEDEIRA',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648417124-3',
  age_range = '+ 3 Anos',
  gender = 'Menina',
  material = 'Plástico',
  color = 'Rosa',
  product_length_mm = 410,
  product_width_mm = 85,
  product_height_mm = 305,
  product_volume_m3 = 0.01062925,
  product_weight_kg = 0.173,
  has_mechanism = true,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '1 microondas
1 batedeira
2 pratos
1 garfo
1 faca
1 colher
1 escumadeira
1 concha
2 espatulas
1 queijo
1 ovo frito
1 ovo
1 frango assado
1 mel
1 milho',
  package_length_mm = 410,
  package_width_mm = 85,
  package_height_mm = 305,
  package_volume_m3 = 0.01062925,
  package_weight_kg = 0.465,
  ncm = '9503.00.80',
  cst = '000',
  dun = '2789648417124-7',
  carton_length_mm = 510,
  carton_width_mm = 420,
  carton_height_mm = 330,
  carton_volume_m3 = 0.070686,
  carton_quantity = 6,
  carton_gross_weight_kg = 3.462,
  pallet_layer_pattern = '5x4',
  pallet_height_m = 1.45,
  pallet_total_units = 20
where code = '7124';

update public.products set
  name = 'DOCE COZINHA PLUS TORRADEIRA E BATEDEIRA',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648417125-0',
  age_range = '+ 3 Anos',
  gender = 'Menina',
  material = 'Plástico',
  color = 'Rosa',
  product_length_mm = 410,
  product_width_mm = 85,
  product_height_mm = 305,
  product_volume_m3 = 0.01062925,
  product_weight_kg = 0.156,
  has_mechanism = true,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '1 torradeira
1 batedeira
2 pratos
1 garfo
1 faca
1 colher
2 pães
5 petit 
1 creme de avelã
1 mel',
  package_length_mm = 410,
  package_width_mm = 85,
  package_height_mm = 305,
  package_volume_m3 = 0.01062925,
  package_weight_kg = 0.445,
  ncm = '9503.00.80',
  cst = '000',
  dun = '2789648417125-4',
  carton_length_mm = 510,
  carton_width_mm = 420,
  carton_height_mm = 330,
  carton_volume_m3 = 0.070686,
  carton_quantity = 6,
  carton_gross_weight_kg = 3.342,
  pallet_layer_pattern = '5x4',
  pallet_height_m = 1.45,
  pallet_total_units = 20
where code = '7125';

update public.products set
  name = 'DOCE COZINHA PLUS BRINCANDO DE COZINHAR',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648417181-6',
  age_range = '+ 3 Anos',
  gender = 'MENINA',
  material = 'PLASTICO',
  color = 'ROSA',
  product_length_mm = 360,
  product_width_mm = 60,
  product_height_mm = 230,
  product_volume_m3 = 0.04968,
  product_weight_kg = 0.284,
  has_mechanism = false,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = 'Fogãozinho de 1 boca com grelha e botão, 
2 panelinhas com tampa, 
3 talheres grandes, 
1 escorredor, 
4 alimentos, 
1 toalha de papel',
  package_length_mm = 360,
  package_width_mm = 60,
  package_height_mm = 230,
  package_volume_m3 = 0.04968,
  package_weight_kg = 0.284,
  ncm = '9503.00.80',
  cst = null,
  dun = '2789648417181-0',
  carton_length_mm = 330,
  carton_width_mm = 250,
  carton_height_mm = 380,
  carton_volume_m3 = 0.03135,
  carton_quantity = 6,
  carton_gross_weight_kg = 2.022,
  pallet_layer_pattern = '14x4',
  pallet_height_m = 1.61,
  pallet_total_units = 56
where code = '7181';

update public.products set
  name = 'DOCE COZINHA PLUS GRILL',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648417182-3',
  age_range = '+ 3 Anos',
  gender = 'MENINA',
  material = 'PLASTICO',
  color = 'ROSA',
  product_length_mm = 360,
  product_width_mm = 60,
  product_height_mm = 230,
  product_volume_m3 = 0.04968,
  product_weight_kg = 0.385,
  has_mechanism = false,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '1 Chapa,
3 Talheres grandes que imitam madeira, 
2 pratinhos, 
2 facas, 
2 colheres, 
2 garfos, 
2 canecas, 
1 saleiro,
1 ovo frito, 
1 toalha de papel',
  package_length_mm = 360,
  package_width_mm = 60,
  package_height_mm = 230,
  package_volume_m3 = 0.04968,
  package_weight_kg = 0.385,
  ncm = '9503.00.80',
  cst = null,
  dun = '2789648417182-7',
  carton_length_mm = 375,
  carton_width_mm = 345,
  carton_height_mm = 335,
  carton_volume_m3 = 0.043340625,
  carton_quantity = 6,
  carton_gross_weight_kg = 2.88,
  pallet_layer_pattern = '9x4',
  pallet_height_m = 1.44,
  pallet_total_units = 36
where code = '7182';

update public.products set
  name = 'DOCE COZINHA PLUS SANDWICH',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648417183-0',
  age_range = '+ 3 Anos',
  gender = 'MENINA',
  material = 'PLASTICO',
  color = 'ROSA',
  product_length_mm = 360,
  product_width_mm = 60,
  product_height_mm = 230,
  product_volume_m3 = 0.04968,
  product_weight_kg = 0.271,
  has_mechanism = false,
  has_sound = false,
  has_light = false,
  battery_type = 'Não possui',
  supported_weight = null,
  toy_category = 'Cozinhas, Kits e Acessórios',
  package_contents = '2 frigideiras
 1 Pão de forma
 1 Hamburgue
 1 folha de Alface
 1 Ovo frito
 1 Tubo de ketchup
 3 talheres que imitam madeira, 
1 toalha de papel',
  package_length_mm = 360,
  package_width_mm = 60,
  package_height_mm = 230,
  package_volume_m3 = 0.04968,
  package_weight_kg = 0.271,
  ncm = '9503.00.80',
  cst = null,
  dun = '2789648417183-4',
  carton_length_mm = 330,
  carton_width_mm = 250,
  carton_height_mm = 380,
  carton_volume_m3 = 0.03135,
  carton_quantity = 6,
  carton_gross_weight_kg = 1.962,
  pallet_layer_pattern = '14x4',
  pallet_height_m = 1.61,
  pallet_total_units = 56
where code = '7183';

update public.products set
  name = 'STUDIO FASHION CELEBRIDADES CORTE&ESCOVA',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648417184-7',
  age_range = '+ 3 Anos',
  gender = 'MENINA',
  material = 'PLASTICO',
  color = 'ROSA',
  product_length_mm = 400,
  product_width_mm = 80,
  product_height_mm = 270,
  product_volume_m3 = 0.0864,
  product_weight_kg = 0.283,
  has_mechanism = true,
  has_sound = false,
  has_light = false,
  battery_type = '02 pilhas AA (inclusas)',
  supported_weight = null,
  toy_category = 'Kits de beleza e Acessórios',
  package_contents = '1 secador eletrônico
1 bico reto
1 bico para pentear
1 difusor
1 pente
2 presilhas
2 bobs com capa
1 tesoura
1 espelho 
2 cartões',
  package_length_mm = 400,
  package_width_mm = 80,
  package_height_mm = 270,
  package_volume_m3 = 0.0864,
  package_weight_kg = 0.283,
  ncm = '9503.00.80',
  cst = null,
  dun = '2789648417184-1',
  carton_length_mm = 475,
  carton_width_mm = 300,
  carton_height_mm = 420,
  carton_volume_m3 = 0.05985,
  carton_quantity = 6,
  carton_gross_weight_kg = 3.588,
  pallet_layer_pattern = '8x3',
  pallet_height_m = 1.4,
  pallet_total_units = 24
where code = '7184';

update public.products set
  name = 'STUDIO FASHION CELEBRIDADES CORTE&HIDRATAÇÃO',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648417185-4',
  age_range = '+ 3 Anos',
  gender = 'MENINA',
  material = 'PLASTICO',
  color = 'ROSA',
  product_length_mm = 400,
  product_width_mm = 80,
  product_height_mm = 270,
  product_volume_m3 = 0.0864,
  product_weight_kg = 0.283,
  has_mechanism = true,
  has_sound = false,
  has_light = false,
  battery_type = '02 pilhas AA (inclusas)',
  supported_weight = null,
  toy_category = 'Kits de beleza e Acessórios',
  package_contents = '1 secador eletrônico
1 bico reto
1 difusor
1 tesoura
1 pente
2 presilhas
2 bobs com capa
1 bisnaga de creme
1 espelho 
2 cartões',
  package_length_mm = 400,
  package_width_mm = 80,
  package_height_mm = 270,
  package_volume_m3 = 0.0864,
  package_weight_kg = 0.283,
  ncm = '9503.00.80',
  cst = null,
  dun = '2789648417185-8',
  carton_length_mm = 475,
  carton_width_mm = 300,
  carton_height_mm = 420,
  carton_volume_m3 = 0.05985,
  carton_quantity = 6,
  carton_gross_weight_kg = 3.51,
  pallet_layer_pattern = '8x3',
  pallet_height_m = 1.4,
  pallet_total_units = 24
where code = '7185';

update public.products set
  name = 'STUDIO FASHION CELEBRIDADES ESCOVA&PENTEADO',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648417186-1',
  age_range = '+ 3 Anos',
  gender = 'MENINA',
  material = 'PLASTICO',
  color = 'ROSA',
  product_length_mm = 400,
  product_width_mm = 80,
  product_height_mm = 270,
  product_volume_m3 = 0.0864,
  product_weight_kg = 0.283,
  has_mechanism = true,
  has_sound = false,
  has_light = false,
  battery_type = '02 pilhas AA (inclusas)',
  supported_weight = null,
  toy_category = 'Kits de beleza e Acessórios',
  package_contents = '1 secador eletrônico
1 bico reto
1 bico para pentear
1 difusor
1 pente
2 presilhas
2 bobs com capa
1 frasco com bomba de Água
1 espelho 
2 cartões',
  package_length_mm = 400,
  package_width_mm = 80,
  package_height_mm = 270,
  package_volume_m3 = 0.0864,
  package_weight_kg = 0.283,
  ncm = '9503.00.80',
  cst = null,
  dun = '2789648417186-5',
  carton_length_mm = 475,
  carton_width_mm = 300,
  carton_height_mm = 420,
  carton_volume_m3 = 0.05985,
  carton_quantity = 6,
  carton_gross_weight_kg = 3.588,
  pallet_layer_pattern = '8x3',
  pallet_height_m = 1.4,
  pallet_total_units = 24
where code = '7186';

update public.products set
  name = 'DOCE COZINHA PLUS CHÁ COM BISCOITOS',
  line = 'PLAY&IMAGINE',
  technical_name = null,
  ean = '789648417205-9',
  age_range = '+ 3 Anos',
  gender = 'Menina',
  material = 'Plástico',
  color = 'COLORIDO',
  product_length_mm = 336,
  product_width_mm = 660,
  product_height_mm = 260,
  product_volume_m3 = 0.0576576,
  product_weight_kg = 0.19,
  has_mechanism = false,
  has_sound = false,
  has_light = false,
  battery_type = 'Não Inclusa / Não possui',
  supported_weight = null,
  toy_category = 'PRIMEIRA INFÂNCIA',
  package_contents = '04 biscoitos 02 colheres 02 pratos 02 xícaras 01 bule grande 01 bule pequeno 01 caldeirão',
  package_length_mm = 336,
  package_width_mm = 660,
  package_height_mm = 260,
  package_volume_m3 = null,
  package_weight_kg = 0.19,
  ncm = '9503.00.80',
  cst = null,
  dun = '2789648417205 3',
  carton_length_mm = 415,
  carton_width_mm = 285,
  carton_height_mm = 355,
  carton_volume_m3 = 0.375,
  carton_quantity = 6,
  carton_gross_weight_kg = null,
  pallet_layer_pattern = null,
  pallet_height_m = null,
  pallet_total_units = null
where code = '7205';
