-- Cardoso HUB — Trade: responsável por loja + enriquecimento cidade/zona (derivado dos nomes)
set lock_timeout='5s';
alter table public.tm_stores add column if not exists default_promoter_id uuid references public.tm_promoters (id);

update public.tm_stores set city='São Paulo', region='Leste' where name='Americanas Aricanduva';
update public.tm_stores set city='São Paulo', region='Sul' where name='Americanas Interlagos';
update public.tm_stores set city='Guarulhos', region='Grande SP' where name='Americanas Internacional';
update public.tm_stores set city='São Paulo', region='Leste' where name='Americanas Itaquera';
update public.tm_stores set city='São Paulo', region='Sul' where name='Americanas Jardim Sul';
update public.tm_stores set city='São Paulo', region='Oeste' where name='Americanas Lapa';
update public.tm_stores set city='São Paulo', region='Sul' where name='Americanas Market Place';
update public.tm_stores set city='Mauá', region='ABC' where name='Americanas Maua';
update public.tm_stores set city='Mogi das Cruzes', region='Grande SP' where name='Americanas Mogi';
update public.tm_stores set city='São Paulo', region='Leste' where name='Americanas Penha';
update public.tm_stores set city='São Bernardo do Campo', region='ABC' where name='Americanas Sbplaza';
update public.tm_stores set city='São Paulo', region='Sul' where name='Americanas Spmarket';
update public.tm_stores set city='Taboão da Serra', region='Grande SP' where name='Americanas Taboao';
update public.tm_stores set city='Taboão da Serra', region='Grande SP' where name='Americanas Taboao Da Serra';
update public.tm_stores set city='São Paulo', region='Leste' where name='Americanas Tatuape';
update public.tm_stores set city='São Paulo', region='Leste' where name='Americanas Uniao';
update public.tm_stores set city='São Paulo', region='Centro' where name='Armarinhos Fernando Bras';
update public.tm_stores set city='Guarulhos', region='Grande SP' where name='Armarinhos Fernando Guarulhos';
update public.tm_stores set city='São Paulo', region='Sul' where name='Armarinhos Fernando Ipiranga';
update public.tm_stores set city='São Paulo', region='Leste' where name='Armarinhos Fernando Mooca';
update public.tm_stores set city='Osasco', region='Grande SP' where name='Armarinhos Fernando Osasco';
update public.tm_stores set city='São Paulo', region='Leste' where name='Armarinhos Fernando S Miguel';
update public.tm_stores set city='São Paulo', region='Sul' where name='Armarinhos Fernando Sto Amaro';
update public.tm_stores set city='Santo André', region='ABC' where name='Armarinhos Fernando Sto Andre';
update public.tm_stores set city='Suzano', region='Grande SP' where name='Armarinhos Fernando Suzano';
update public.tm_stores set city='São Paulo', region='Leste' where name='Armarinhos Fernando Tatuape';
update public.tm_stores set city='Itapevi', region='Grande SP' where name='Atacadão Amador Bueno';
update public.tm_stores set city='São Paulo', region='Leste' where name='Atacadão Aricanduva';
update public.tm_stores set city='Santo André', region='ABC' where name='Atacadão Capuava';
update public.tm_stores set city='Guarulhos', region='Grande SP' where name='Atacadão Centro Gua';
update public.tm_stores set city='São Paulo', region='Sul' where name='Atacadão Cupece';
update public.tm_stores set city='Diadema', region='ABC' where name='Atacadão Diadema';
update public.tm_stores set city='Guarulhos', region='Grande SP' where name='Atacadão Dutra';
update public.tm_stores set city='Guarulhos', region='Grande SP' where name='Atacadão Gua Centro';
update public.tm_stores set city='Guarulhos', region='Grande SP' where name='Atacadão Gua I';
update public.tm_stores set city='Guarulhos', region='Grande SP' where name='Atacadão Gua Ii';
update public.tm_stores set city='Guarulhos', region='Grande SP' where name='Atacadão Guarulhos 2';
update public.tm_stores set city='Indaiatuba', region='Interior' where name='Atacadão Indaiatuba';
update public.tm_stores set city='São Paulo', region='Sul' where name='Atacadão Ipiranga';
update public.tm_stores set city='São Paulo', region='Oeste' where name='Atacadão Itaim';
update public.tm_stores set city='São Paulo', region='Leste' where name='Atacadão Itaquera';
update public.tm_stores set city='São Paulo', region='Sul' where name='Atacadão Jacui';
update public.tm_stores set city='Osasco', region='Grande SP' where name='Atacadão Osasco';
update public.tm_stores set city='Guarulhos', region='Grande SP' where name='Atacadão Otavio Braga';
update public.tm_stores set city='São Paulo', region='Sul' where name='Atacadão Parelheiros';
update public.tm_stores set city='São Paulo', region='Leste' where name='Atacadão Penha';
update public.tm_stores set city='Diadema', region='ABC' where name='Atacadão Piraporinha';
update public.tm_stores set city='São Paulo', region='Sul' where name='Atacadão Santo Amaro';
update public.tm_stores set city='São Bernardo do Campo', region='ABC' where name='Atacadão Sb Centro';
update public.tm_stores set city='Santo André', region='ABC' where name='Atacadão Sto Andre';
update public.tm_stores set city='Suzano', region='Grande SP' where name='Atacadão Suzano';
update public.tm_stores set city='Taboão da Serra', region='Grande SP' where name='Atacadão Taboao I';
update public.tm_stores set city='Taboão da Serra', region='Grande SP' where name='Atacadão Taboao Ii';
update public.tm_stores set city='Taboão da Serra', region='Grande SP' where name='Atacadão Taboao Loja 1';
update public.tm_stores set city='Taboão da Serra', region='Grande SP' where name='Atacadão Taboao Loja 2';
update public.tm_stores set city='São Paulo', region='Norte' where name='Atacadão Vila Guilherme';
update public.tm_stores set city='São Paulo', region='Norte' where name='Atacadão Vila Maria';
update public.tm_stores set city='São Paulo', region='Leste' where name='B-Mart Brinquedos Itaquera';
update public.tm_stores set city='Taboão da Serra', region='Grande SP' where name='B-Mart Brinquedos Taboao';
update public.tm_stores set city='São Paulo', region='Centro' where name='Barracão Centro';
update public.tm_stores set city='São Paulo', region='Oeste' where name='Barracão Itaim';
update public.tm_stores set city='Guarulhos', region='Grande SP' where name='Barracão Pimentas';
update public.tm_stores set city='São Paulo', region='Leste' where name='Barracão S Miguel';
update public.tm_stores set city='São Paulo', region='Sul' where name='Barracão Sto Amaro';
update public.tm_stores set city='São Paulo', region='Leste' where name='Carrefour Analia';
update public.tm_stores set city='São Paulo', region='Leste' where name='PB Kids Analia';
update public.tm_stores set city='São Paulo', region='Oeste' where name='PB Kids Eldorado';
update public.tm_stores set city='Cotia', region='Grande SP' where name='PB Kids G Vianna';
update public.tm_stores set city='Cotia', region='Grande SP' where name='PB Kids Gra Vianna';
update public.tm_stores set city='Cotia', region='Grande SP' where name='PB Kids Granja Viana';
update public.tm_stores set city='São Paulo', region='Sul' where name='PB Kids Jardim Sul';
update public.tm_stores set city='Guarulhos', region='Grande SP' where name='PB Kids Maia';
update public.tm_stores set city='São Paulo', region='Oeste' where name='PB Kids Morumbi';
update public.tm_stores set city='Barueri', region='Grande SP' where name='PB Kids Tambore';
update public.tm_stores set city='Atibaia', region='Interior' where name='Pirueta Atibaia';
update public.tm_stores set city='São Paulo', region='Leste' where name='Pirueta C Plaza';
update public.tm_stores set city='São Paulo', region='Leste' where name='Pirueta Centralplaza';
update public.tm_stores set city='São Paulo', region='Leste' where name='Pirueta Ragueb';
update public.tm_stores set city='Taubaté', region='Interior' where name='Pirueta Taubate';
update public.tm_stores set city='São Paulo', region='Leste' where name='Pirueta V Prudente';
update public.tm_stores set city='São Paulo', region='Leste' where name='Ri Happy Aricanduva';
update public.tm_stores set city='São Paulo', region='Centro' where name='Ri Happy Augusta';
update public.tm_stores set city='São Paulo', region='Centro' where name='Ri Happy Cidade De S Paulo';
update public.tm_stores set city='São Paulo', region='Oeste' where name='Ri Happy Eldorado';
update public.tm_stores set city='São Paulo', region='Sul' where name='Ri Happy Interlagos';
update public.tm_stores set city='Guarulhos', region='Grande SP' where name='Ri Happy Internacional';
update public.tm_stores set city='São Paulo', region='Oeste' where name='Ri Happy Itaim';
update public.tm_stores set city='São Paulo', region='Leste' where name='Ri Happy Itaquera';
update public.tm_stores set city='Mauá', region='ABC' where name='Ri Happy Maua';
update public.tm_stores set city='Mogi das Cruzes', region='Grande SP' where name='Ri Happy Mogi';
update public.tm_stores set city='São Paulo', region='Oeste' where name='Ri Happy Morumbi';
update public.tm_stores set city='São Paulo', region='Oeste' where name='Ri Happy Morumbi Town';
update public.tm_stores set city='Guarulhos', region='Grande SP' where name='Ri Happy Otto Baumgard';
update public.tm_stores set city='São Paulo', region='Leste' where name='Ri Happy Pca Da Moca';
update public.tm_stores set city='São Paulo', region='Leste' where name='Ri Happy Penha';
update public.tm_stores set city='São Paulo', region='Oeste' where name='Ri Happy Raposo';
update public.tm_stores set city='São Bernardo do Campo', region='ABC' where name='Ri Happy Sb Plaza';
update public.tm_stores set city='São Paulo', region='Centro' where name='Ri Happy Shop Cid Sao Paulo';
update public.tm_stores set city='São Paulo', region='Sul' where name='Ri Happy Sp Market';
update public.tm_stores set city='São Paulo', region='Leste' where name='Ri Happy Tatuape';
update public.tm_stores set city='São Paulo', region='Norte' where name='Ri Happy Tiete';
update public.tm_stores set city='São Paulo', region='Norte' where name='Ri Happy Tucuruvi';
update public.tm_stores set city='São Paulo', region='Leste' where name='Ri Happy Uniao';
update public.tm_stores set city='São Paulo', region='Sul' where name='Ri Happy V Mariana';
update public.tm_stores set city='São Paulo', region='Sul' where name='Ri Happy Vila Mariana';
update public.tm_stores set city='São Paulo', region='Oeste' where name='Ri Happy Villa Lobos';