-- Cardoso HUB — Trade: endereços/cidade/zona (planilha do usuário)
set lock_timeout='5s';

update public.tm_stores set city='São Paulo', region='Leste', address='Av. Aricanduva, 5.555 - Aricanduva, São Paulo - SP, 03527-000' where name='Americanas Aricanduva';
update public.tm_stores set city='São Paulo', region='Sul', address='Av. Interlagos, 2.255 - Campo Grande, São Paulo - SP, 04661-200' where name='Americanas Interlagos';
update public.tm_stores set city='Guarulhos', region='Grande SP', address='Rod. Pres. Dutra, s/n, Km 230 - Vila Itapegica, Guarulhos - SP, 07034-911' where name='Americanas Internacional';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. José Pinheiro Borges, s/n - Itaquera, São Paulo - SP, 08220-900' where name='Americanas Itaquera';
update public.tm_stores set city='São Paulo', region='Sul', address='Av. Giovanni Gronchi, 5.819 - Vila Andrade, São Paulo - SP, 05724-003' where name='Americanas Jardim Sul';
update public.tm_stores set city='São Paulo', region='Oeste', address='Rua Catão, 72 - Vila Romana, São Paulo - SP' where name='Americanas Lapa';
update public.tm_stores set city='São Paulo', region='Sul', address='Av. Doutor Chucri Zaidan, 902 - Vila Cordeiro, São Paulo - SP, 04583-110' where name='Americanas Market Place';
update public.tm_stores set city='Mauá', region='ABC', address='Av. Gov. Mário Covas Júnior, 1 - Centro, Mauá - SP, 09310-000' where name='Americanas Maua';
update public.tm_stores set city='Mogi das Cruzes', region='Grande SP', address='Av. Vereador Narciso Yague Guimarães, 1.001 - Jardim Armênia, Mogi das Cruzes - SP, 08780-000' where name='Americanas Mogi';
update public.tm_stores set city='São Paulo', region='Leste', address='Rua Dr. João Ribeiro, 304 - Penha de França, São Paulo - SP, 03634-000' where name='Americanas Penha';
update public.tm_stores set city='São Bernardo do Campo', region='ABC', address='Av. Rotary, 624 - Centro, São Bernardo do Campo - SP, 09721-000' where name='Americanas Sbplaza';
update public.tm_stores set city='', region='', address='Rod. Régis Bittencourt, 2.643 - Cidade Intercap, Taboão da Serra - SP, 06768-200' where name='Americanas Shopping Taboao';
update public.tm_stores set city='São Paulo', region='Sul', address='Av. das Nações Unidas, 22.540 - Santo Amaro, São Paulo - SP, 04795-000' where name='Americanas Spmarket';
update public.tm_stores set city='Taboão da Serra', region='Grande SP', address='Rod. Régis Bittencourt, 2.643 - Cidade Intercap, Taboão da Serra - SP, 06768-200' where name='Americanas Taboao';
update public.tm_stores set city='Taboão da Serra', region='Grande SP', address='Rod. Régis Bittencourt, 2.643 - Cidade Intercap, Taboão da Serra - SP, 06768-200' where name='Americanas Taboao Da Serra';
update public.tm_stores set city='São Paulo', region='Leste', address='Rua Domingos Agostim, 91 - Tatuapé, São Paulo - SP, 03306-010' where name='Americanas Tatuape';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. dos Autonomistas, 1.400 - Vila Yara, Osasco - SP, 06020-010' where name='Americanas Uniao';
update public.tm_stores set city='', region='', address='Rua 25 de Março, 864/872 - Centro, São Paulo - SP, 01021-100' where name='Armarinhos Fernando';
update public.tm_stores set city='São Paulo', region='Centro', address='Rua Maria Marcolina, 48 - Brás, São Paulo - SP, 03011-000' where name='Armarinhos Fernando Bras';
update public.tm_stores set city='Guarulhos', region='Grande SP', address='Praça Tereza Cristina, 37/47 - Centro, Guarulhos - SP, 07023-070' where name='Armarinhos Fernando Guarulhos';
update public.tm_stores set city='São Paulo', region='Sul', address='Rua Silva Bueno, 2.533 - Ipiranga, São Paulo - SP, 04208-053' where name='Armarinhos Fernando Ipiranga';
update public.tm_stores set city='São Paulo', region='Leste', address='Rua Taquari, 156 - Mooca, São Paulo - SP, 03166-000' where name='Armarinhos Fernando Mooca';
update public.tm_stores set city='Osasco', region='Grande SP', address='Rua Tenente Avelar Pires de Azevedo, 140 - Centro, Osasco - SP' where name='Armarinhos Fernando Osasco';
update public.tm_stores set city='', region='', address='Alameda Santo Amaro, 121 - Santo Amaro, São Paulo - SP, 04745-001' where name='Armarinhos Fernando S Amaro';
update public.tm_stores set city='São Paulo', region='Leste', address='Rua Arlindo Colaço, 399/432 e 427 - São Miguel Paulista, São Paulo - SP' where name='Armarinhos Fernando S Miguel';
update public.tm_stores set city='São Paulo', region='Sul', address='Alameda Santo Amaro, 121 - Santo Amaro, São Paulo - SP, 04745-001' where name='Armarinhos Fernando Sto Amaro';
update public.tm_stores set city='Santo André', region='ABC', address='Rua General Glicério, 42 - Centro, Santo André - SP, 09015-010' where name='Armarinhos Fernando Sto Andre';
update public.tm_stores set city='Suzano', region='Grande SP', address='Rua General Francisco Glicério - Centro, Suzano - SP, 08674-001' where name='Armarinhos Fernando Suzano';
update public.tm_stores set city='São Paulo', region='Leste', address='Rua Aguapeí, 635 - Tatuapé, São Paulo - SP, 03325-000' where name='Armarinhos Fernando Tatuape';
update public.tm_stores set city='', region='', address='Não localizado com segurança' where name='Armarinhos Fernando Yiete';
update public.tm_stores set city='Itapevi', region='Grande SP', address='Av. Feres Nacif Chaluppe, 1.250 - Centro, Itapevi - SP' where name='Atacadão Amador Bueno';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. Aricanduva, 3.600 - Vila Califórnia, São Paulo - SP, 03490-000' where name='Atacadão Aricanduva';
update public.tm_stores set city='Santo André', region='ABC', address='Av. dos Estados, 6.500 - Capuava, Santo André - SP' where name='Atacadão Capuava';
update public.tm_stores set city='Guarulhos', region='Grande SP', address='Rua José Bernardo Medeiros, 237 - São Francisco, Guarulhos - SP, 07013-050' where name='Atacadão Centro Gua';
update public.tm_stores set city='São Paulo', region='Sul', address='Av. Cupecê, 1.995 - Cupecê, São Paulo - SP' where name='Atacadão Cupece';
update public.tm_stores set city='Diadema', region='ABC', address='Av. Piraporinha, 1.670 - Piraporinha, Diadema - SP' where name='Atacadão Diadema';
update public.tm_stores set city='Guarulhos', region='Grande SP', address='Rod. Presidente Dutra, Km 223 - Guarulhos - SP' where name='Atacadão Dutra';
update public.tm_stores set city='Guarulhos', region='Grande SP', address='Rua José Bernardo Medeiros, 237 - São Francisco, Guarulhos - SP, 07013-050' where name='Atacadão Gua Centro';
update public.tm_stores set city='Guarulhos', region='Grande SP', address='Rod. Presidente Dutra, Km 230 - Vila Itapegica, Guarulhos - SP' where name='Atacadão Gua I';
update public.tm_stores set city='Guarulhos', region='Grande SP', address='Rod. Presidente Dutra, Km 230 - Vila Itapegica, Guarulhos - SP' where name='Atacadão Gua Ii';
update public.tm_stores set city='Guarulhos', region='Grande SP', address='Rod. Presidente Dutra, Km 230 - Vila Itapegica, Guarulhos - SP' where name='Atacadão Guarulhos 2';
update public.tm_stores set city='Indaiatuba', region='Interior', address='Av. Francisco de Paula Leite, 2.300 - Indaiatuba - SP' where name='Atacadão Indaiatuba';
update public.tm_stores set city='São Paulo', region='Sul', address='Rua do Manifesto, 931 - Ipiranga, São Paulo - SP, 04209-000' where name='Atacadão Ipiranga';
update public.tm_stores set city='São Paulo', region='Oeste', address='Av. Marechal Tito, 2.501 - São Miguel Paulista, São Paulo - SP, 08022-010' where name='Atacadão Itaim';
update public.tm_stores set city='São Paulo', region='Leste', address='Estrada do Pêssego, 100 - Itaquera, São Paulo - SP, 08260-000' where name='Atacadão Itaquera';
update public.tm_stores set city='São Paulo', region='Sul', address='Av. Dr. Custódio de Lima, 297 - Parque Cruzeiro do Sul, São Paulo - SP, 08071-000' where name='Atacadão Jacui';
update public.tm_stores set city='Osasco', region='Grande SP', address='Av. dos Autonomistas, 1.400 - Vila Yara, Osasco - SP, 06020-010' where name='Atacadão Osasco';
update public.tm_stores set city='Guarulhos', region='Grande SP', address='Av. Otávio Braga de Mesquita, 2.120 - Vila Fátima, Guarulhos - SP' where name='Atacadão Otavio Braga';
update public.tm_stores set city='São Paulo', region='Sul', address='Av. Sen. Teotônio Vilela, 8.030 - Jardim São Rafael, São Paulo - SP, 04864-002' where name='Atacadão Parelheiros';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. Amador Bueno da Veiga, 2.521 - Penha de França, São Paulo - SP, 03653-000' where name='Atacadão Penha';
update public.tm_stores set city='Diadema', region='ABC', address='Av. Piraporinha, 1.670 - Piraporinha, Diadema - SP' where name='Atacadão Piraporinha';
update public.tm_stores set city='São Paulo', region='Sul', address='Estrada do M''Boi Mirim, 380 - Parque Novo Santo Amaro, São Paulo - SP, 04905-020' where name='Atacadão Santo Amaro';
update public.tm_stores set city='São Bernardo do Campo', region='ABC', address='Av. Senador Vergueiro, 2.500 - São Bernardo do Campo - SP' where name='Atacadão Sb Centro';
update public.tm_stores set city='Santo André', region='ABC', address='Av. dos Estados, 6.500 - Santo André - SP' where name='Atacadão Sto Andre';
update public.tm_stores set city='Suzano', region='Grande SP', address='Av. Jorge Bei Maluf, 3.200 - Suzano - SP' where name='Atacadão Suzano';
update public.tm_stores set city='Taboão da Serra', region='Grande SP', address='Rod. Régis Bittencourt, Km 271,5 - Taboão da Serra - SP' where name='Atacadão Taboao I';
update public.tm_stores set city='Taboão da Serra', region='Grande SP', address='Rod. Régis Bittencourt, Km 271,5 - Taboão da Serra - SP' where name='Atacadão Taboao Ii';
update public.tm_stores set city='', region='', address='Rod. Régis Bittencourt, Km 271,5 - Taboão da Serra - SP' where name='Atacadão Taboao Lj I';
update public.tm_stores set city='Taboão da Serra', region='Grande SP', address='Rod. Régis Bittencourt, Km 271,5 - Taboão da Serra - SP' where name='Atacadão Taboao Loja 1';
update public.tm_stores set city='Taboão da Serra', region='Grande SP', address='Rod. Régis Bittencourt, Km 271,5 - Taboão da Serra - SP' where name='Atacadão Taboao Loja 2';
update public.tm_stores set city='São Paulo', region='Norte', address='Av. Joaquina Ramalho, 340 - Vila Guilherme, São Paulo - SP, 02065-000' where name='Atacadão Vila Guilherme';
update public.tm_stores set city='São Paulo', region='Norte', address='Av. Morvan Dias de Figueiredo, 6.157 - Vila Maria, São Paulo - SP, 02170-901' where name='Atacadão Vila Maria';
update public.tm_stores set city='', region='', address='Não localizado com segurança' where name='B-Mart Brinquedos';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. José Pinheiro Borges, s/n - Itaquera, São Paulo - SP, 08220-900' where name='B-Mart Brinquedos Itaquera';
update public.tm_stores set city='Taboão da Serra', region='Grande SP', address='Rod. Régis Bittencourt, 2.646, Km 271,5 - Jardim Helena, Taboão da Serra - SP, 06768-200' where name='B-Mart Brinquedos Taboao';
update public.tm_stores set city='', region='', address='Não localizado com segurança' where name='Barracão';
update public.tm_stores set city='São Paulo', region='Centro', address='Não localizado com segurança' where name='Barracão Centro';
update public.tm_stores set city='São Paulo', region='Oeste', address='Av. Marechal Tito, 2.647 - São Miguel Paulista, São Paulo - SP, 08022-000' where name='Barracão Itaim';
update public.tm_stores set city='Guarulhos', region='Grande SP', address='Estr. Pres. Juscelino K. de Oliveira, 4.252 - Jardim Albertina, Guarulhos - SP, 07252-000' where name='Barracão Pimentas';
update public.tm_stores set city='São Paulo', region='Leste', address='Rua Beraldo Marcondes, 181 - São Miguel Paulista, São Paulo - SP, 08010-090' where name='Barracão S Miguel';
update public.tm_stores set city='São Paulo', region='Sul', address='Rua Cap. Tiago Luz, 41 - Santo Amaro, São Paulo - SP, 04751-010' where name='Barracão Sto Amaro';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. Regente Feijó, 1.759 - Vila Regente Feijó, São Paulo - SP, 03342-000' where name='Carrefour Analia';
update public.tm_stores set city='', region='', address='Não localizado com segurança' where name='Magazine';
update public.tm_stores set city='', region='', address='Não localizado com segurança' where name='MiniPreço';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. Regente Feijó, 1.739 - Shopping Anália Franco, São Paulo - SP' where name='PB Kids Analia';
update public.tm_stores set city='São Paulo', region='Oeste', address='Av. Rebouças, 3.970 - Shopping Eldorado, São Paulo - SP' where name='PB Kids Eldorado';
update public.tm_stores set city='Cotia', region='Grande SP', address='Rod. Raposo Tavares, Km 23,5, 2.780 - Granja Viana, Cotia - SP' where name='PB Kids G Vianna';
update public.tm_stores set city='Cotia', region='Grande SP', address='Rod. Raposo Tavares, Km 23,5, 2.780 - Granja Viana, Cotia - SP' where name='PB Kids Gra Vianna';
update public.tm_stores set city='', region='', address='Rod. Raposo Tavares, Km 23,5, 2.780 - Granja Viana, Cotia - SP' where name='PB Kids Granja V';
update public.tm_stores set city='Cotia', region='Grande SP', address='Rod. Raposo Tavares, Km 23,5, 2.780 - Granja Viana, Cotia - SP' where name='PB Kids Granja Viana';
update public.tm_stores set city='São Paulo', region='Sul', address='Av. Giovanni Gronchi, 5.819 - Jardim Sul, São Paulo - SP' where name='PB Kids Jardim Sul';
update public.tm_stores set city='Guarulhos', region='Grande SP', address='Av. Bartolomeu de Carlos, 230 - Parque Shopping Maia, Guarulhos - SP, 07097-420' where name='PB Kids Maia';
update public.tm_stores set city='São Paulo', region='Oeste', address='Av. Roque Petroni Jr., 1.089 - Morumbi Shopping, São Paulo - SP' where name='PB Kids Morumbi';
update public.tm_stores set city='Barueri', region='Grande SP', address='Av. Piracema, 669 - Shopping Tamboré, Barueri - SP' where name='PB Kids Tambore';
update public.tm_stores set city='', region='', address='Av. Sapopemba, 7.659 - Jardim Adutora, São Paulo - SP' where name='Pirueta';
update public.tm_stores set city='Atibaia', region='Interior', address='Rua Luiz Onofre de Amorim, 50 - Parque Fernão Dias, Atibaia - SP' where name='Pirueta Atibaia';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. Dr. Francisco Mesquita, 1.000 - Central Plaza, São Paulo - SP' where name='Pirueta C Plaza';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. Dr. Francisco Mesquita, 1.000 - Central Plaza, São Paulo - SP' where name='Pirueta Centralplaza';
update public.tm_stores set city='', region='', address='Não localizado com segurança' where name='Pirueta Grimalde';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. Ragueb Chohfi, 3.118 - Parque Boa Esperança, São Paulo - SP' where name='Pirueta Ragueb';
update public.tm_stores set city='Taubaté', region='Interior', address='Av. Dom Pedro I, 7.181 - Jardim Baronesa, Taubaté - SP, 12091-000' where name='Pirueta Taubate';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. Prof. Luiz Ignácio Anhaia Mello, 2.547 - Vila Prudente, São Paulo - SP, 03155-100' where name='Pirueta V Prudente';
update public.tm_stores set city='', region='', address='Rua Voluntários da Pátria, 1.898/1.902-1.908 - Santana, São Paulo - SP, 02010-600' where name='Renascer';
update public.tm_stores set city='', region='', address='Não localizado com segurança' where name='Renascer L1';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. Aricanduva, 5.555 - Shopping Aricanduva, São Paulo - SP' where name='Ri Happy Aricanduva';
update public.tm_stores set city='São Paulo', region='Centro', address='Rua Augusta, 2.529/2.533 - São Paulo - SP' where name='Ri Happy Augusta';
update public.tm_stores set city='', region='', address='Av. Paulista, 1.230 - São Paulo - SP' where name='Ri Happy Cid De Sao Paulo';
update public.tm_stores set city='São Paulo', region='Centro', address='Av. Paulista, 1.230 - São Paulo - SP' where name='Ri Happy Cidade De S Paulo';
update public.tm_stores set city='São Paulo', region='Oeste', address='Av. Rebouças, 3.970 - Shopping Eldorado, São Paulo - SP' where name='Ri Happy Eldorado';
update public.tm_stores set city='São Paulo', region='Sul', address='Av. Interlagos, 2.255 - São Paulo - SP' where name='Ri Happy Interlagos';
update public.tm_stores set city='Guarulhos', region='Grande SP', address='Rod. Pres. Dutra, s/n, Km 230 - Guarulhos - SP' where name='Ri Happy Internacional';
update public.tm_stores set city='São Paulo', region='Oeste', address='Rua João Cachoeira, 138/140/148 - Itaim Bibi, São Paulo - SP' where name='Ri Happy Itaim';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. José Pinheiro Borges, s/n - Metrô Itaquera, São Paulo - SP, 08220-900' where name='Ri Happy Itaquera';
update public.tm_stores set city='Mauá', region='ABC', address='Av. Gov. Mário Covas Júnior, 1 - Mauá Plaza Shopping, Mauá - SP' where name='Ri Happy Maua';
update public.tm_stores set city='Mogi das Cruzes', region='Grande SP', address='Av. Vereador Narciso Yague Guimarães, 1.001 - Mogi das Cruzes - SP' where name='Ri Happy Mogi';
update public.tm_stores set city='São Paulo', region='Oeste', address='Av. Giovanni Gronchi, 5.930 - Morumbi Town, São Paulo - SP' where name='Ri Happy Morumbi';
update public.tm_stores set city='', region='', address='Av. Giovanni Gronchi, 5.930 - Morumbi Town, São Paulo - SP' where name='Ri Happy Morumbi Tow';
update public.tm_stores set city='São Paulo', region='Oeste', address='Av. Giovanni Gronchi, 5.930 - Morumbi Town, São Paulo - SP' where name='Ri Happy Morumbi Town';
update public.tm_stores set city='Guarulhos', region='Grande SP', address='Av. Otto Baumgart, 800 - Loja 2, São Paulo - SP' where name='Ri Happy Otto Baumgard';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. Piraporinha, 1.000 - Praça da Moça, Diadema - SP' where name='Ri Happy Pca Da Moca';
update public.tm_stores set city='São Paulo', region='Leste', address='Rua Dr. João Ribeiro, 304 - Shopping Penha, São Paulo - SP' where name='Ri Happy Penha';
update public.tm_stores set city='São Paulo', region='Oeste', address='Rod. Raposo Tavares, Km 14,5 - Raposo Shopping, São Paulo - SP' where name='Ri Happy Raposo';
update public.tm_stores set city='São Bernardo do Campo', region='ABC', address='Av. Rotary, 624 - São Bernardo Plaza, São Bernardo do Campo - SP, 09721-000' where name='Ri Happy Sb Plaza';
update public.tm_stores set city='São Paulo', region='Centro', address='Av. Paulista, 1.230 - São Paulo - SP' where name='Ri Happy Shop Cid Sao Paulo';
update public.tm_stores set city='São Paulo', region='Sul', address='Av. das Nações Unidas, 22.540 - SP Market, São Paulo - SP, 04795-000' where name='Ri Happy Sp Market';
update public.tm_stores set city='São Paulo', region='Leste', address='Rua Melo Freire, s/n - Metrô Tatuapé, São Paulo - SP' where name='Ri Happy Tatuape';
update public.tm_stores set city='São Paulo', region='Norte', address='Av. Raimundo Pereira de Magalhães, 1.465 - Tietê Plaza, São Paulo - SP' where name='Ri Happy Tiete';
update public.tm_stores set city='São Paulo', region='Norte', address='Av. Dr. Antônio Maria Laet, 566 - Metrô Tucuruvi, São Paulo - SP' where name='Ri Happy Tucuruvi';
update public.tm_stores set city='São Paulo', region='Leste', address='Av. dos Autonomistas, 1.400 - Shopping União, Osasco - SP, 06020-010' where name='Ri Happy Uniao';
update public.tm_stores set city='São Paulo', region='Sul', address='Rua Domingos de Moraes, 1.321/1.331 - Vila Mariana, São Paulo - SP' where name='Ri Happy V Mariana';
update public.tm_stores set city='São Paulo', region='Sul', address='Rua Domingos de Moraes, 1.321/1.331 - Vila Mariana, São Paulo - SP' where name='Ri Happy Vila Mariana';
update public.tm_stores set city='São Paulo', region='Oeste', address='Av. das Nações Unidas, 4.777 - Villa-Lobos, São Paulo - SP' where name='Ri Happy Villa Lobos';