-- Cardoso Marketing Hub — Trade: preenche cidade + zona das lojas a partir dos endereços.
-- Só preenche onde está vazio (não sobrescreve cadastro existente). Roda depois de 0087. Idempotente.

set lock_timeout = '5s';

update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Pirueta - Vila Prudente';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Pirueta- Vila Diva';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Pirueta-jardim Grimaldi';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Pirueta- Jardim Ibitirama';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo') where name='Pirueta- Boa Esperança';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Oeste') where name='Pirueta - Continental';
update public.tm_stores set city=coalesce(nullif(city,''), 'Atibaia'), region=coalesce(nullif(region,''), 'Interior') where name='Pirueta Atibaia';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Mei Magazine- Mateo Bei';
update public.tm_stores set city=coalesce(nullif(city,''), 'Taubaté'), region=coalesce(nullif(region,''), 'Interior') where name='Pirueta Taubaté- Taubaté';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Armarinhos Fernando Mooca';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Armarinhos Fernando Tatuape';
update public.tm_stores set city=coalesce(nullif(city,''), 'Osasco'), region=coalesce(nullif(region,''), 'Grande SP') where name='Armarinhos Fernando Osasco';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Armarinhos Fernando-São Miguel';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Centro') where name='Armarinhos Fernando Bras';
update public.tm_stores set city=coalesce(nullif(city,''), 'Guarulhos'), region=coalesce(nullif(region,''), 'Grande SP') where name='Armarinhos Fernando Guarulhos';
update public.tm_stores set city=coalesce(nullif(city,''), 'Santo André'), region=coalesce(nullif(region,''), 'ABC') where name='Armarinhos Fernando-Santo André';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Bernardo do Campo'), region=coalesce(nullif(region,''), 'ABC') where name='Armarinhos Fernando São Bernardo do Campos';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Sul') where name='Armarinhos Fernando Santo Amaro';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Sul') where name='Armarinhos Fernando Ipiranga';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Centro') where name='Armarinhos Fernando Suzano';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Sul') where name='Barracão Santo Amaro';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Sul') where name='Barracão Parelheiros';
update public.tm_stores set city=coalesce(nullif(city,''), 'Guarulhos'), region=coalesce(nullif(region,''), 'Grande SP') where name='Barracão Guarulhos';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Barracão Itaim Paulista';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Barracão São Miguel';
update public.tm_stores set city=coalesce(nullif(city,''), 'Guarulhos'), region=coalesce(nullif(region,''), 'Grande SP') where name='Barracão Pimentas';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Barracão Sapopemba';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Barracão Mateo Bei';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='RiHappy Itapura';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Sul') where name='Ri Happy Interlagos';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Sul') where name='Ri Happy Sp Market';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Ri Happy Tatuape';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Ri Happy Itaquera';
update public.tm_stores set city=coalesce(nullif(city,''), 'Guarulhos'), region=coalesce(nullif(region,''), 'Grande SP') where name='RiHappy Guarulhos';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Ri Happy Aricanduva';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Ri Happy Penha';
update public.tm_stores set city=coalesce(nullif(city,''), 'Mauá'), region=coalesce(nullif(region,''), 'ABC') where name='Ri Happy Maua';
update public.tm_stores set city=coalesce(nullif(city,''), 'Santo André'), region=coalesce(nullif(region,''), 'ABC') where name='RiHappy Santo André';
update public.tm_stores set city=coalesce(nullif(city,''), 'Diadema'), region=coalesce(nullif(region,''), 'ABC') where name='RiHappy Diadema';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Norte') where name='RiHappy Vila Guilherme';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Norte') where name='Ri Happy Tucuruvi';
update public.tm_stores set city=coalesce(nullif(city,''), 'Osasco'), region=coalesce(nullif(region,''), 'Grande SP') where name='RiHappy  Osasco';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Norte') where name='RiHappy Pirituba';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo') where name='RiHappy Raposo Tavares';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Centro') where name='RiHappy Bela Vista';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Sul') where name='Ri Happy Vila Mariana';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='PBks Tatuapé';
update public.tm_stores set city=coalesce(nullif(city,''), 'Guarulhos'), region=coalesce(nullif(region,''), 'Grande SP') where name='PBks Guarulhos';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='PBks Mooca';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Oeste') where name='PBks Pinheiros';
update public.tm_stores set city=coalesce(nullif(city,''), 'Barueri'), region=coalesce(nullif(region,''), 'Grande SP') where name='PBks Barueri';
update public.tm_stores set city=coalesce(nullif(city,''), 'Cotia'), region=coalesce(nullif(region,''), 'Grande SP') where name='PBks Cotia';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Mini Preçp Grajaú';
update public.tm_stores set city=coalesce(nullif(city,''), 'Diadema'), region=coalesce(nullif(region,''), 'ABC') where name='BemBella Diadema';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Atacadão Parelheiros';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Norte') where name='Atacadão Vila Maria';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Atacadão Aricanduva';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Atacadão Tatuapé';
update public.tm_stores set city=coalesce(nullif(city,''), 'Taboão da Serra'), region=coalesce(nullif(region,''), 'Grande SP') where name='Atacadão Maúa';
update public.tm_stores set city=coalesce(nullif(city,''), 'Santo André'), region=coalesce(nullif(region,''), 'ABC') where name='Atacadão Santo André';
update public.tm_stores set city=coalesce(nullif(city,''), 'Taboão da Serra'), region=coalesce(nullif(region,''), 'Grande SP') where name='Atacadão Taboao I';
update public.tm_stores set city=coalesce(nullif(city,''), 'Taboão da Serra'), region=coalesce(nullif(region,''), 'Grande SP') where name='Atacadão Taboao Ii';
update public.tm_stores set city=coalesce(nullif(city,''), 'Diadema'), region=coalesce(nullif(region,''), 'ABC') where name='Atacadão Diadema';
update public.tm_stores set city=coalesce(nullif(city,''), 'Guarulhos'), region=coalesce(nullif(region,''), 'Grande SP') where name='Atacadão Guarulhos';
update public.tm_stores set city=coalesce(nullif(city,''), 'Guarulhos'), region=coalesce(nullif(region,''), 'Grande SP') where name='Atacadão Guarulhos centro';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Atacadão Penha';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Norte') where name='Atacadão Vila Guilherme';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Atacadão Itaquera';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Sul') where name='Atacadão Ipiranga';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Norte') where name='Atacadão Taípas';
update public.tm_stores set city=coalesce(nullif(city,''), 'Osasco'), region=coalesce(nullif(region,''), 'Grande SP') where name='Atacadão Osasco';
update public.tm_stores set city=coalesce(nullif(city,''), 'Guarulhos'), region=coalesce(nullif(region,''), 'Grande SP') where name='Atacadão Dutra';
update public.tm_stores set city=coalesce(nullif(city,''), 'Suzano'), region=coalesce(nullif(region,''), 'Grande SP') where name='Atacadão Suzano';
update public.tm_stores set city=coalesce(nullif(city,''), 'Taboão da Serra'), region=coalesce(nullif(region,''), 'Grande SP') where name='Bmart Taboão';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Bmart Itaquera';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Americanas Itaquera';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Americanas Aricanduva';
update public.tm_stores set city=coalesce(nullif(city,''), 'Taboão da Serra'), region=coalesce(nullif(region,''), 'Grande SP') where name='Americanas Taboao';
update public.tm_stores set city=coalesce(nullif(city,''), 'Guarulhos'), region=coalesce(nullif(region,''), 'Grande SP') where name='Americanas Guarulhos';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Oeste') where name='Americanas Lapa';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Sul') where name='Americanas Interlagos';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Sul') where name='Americanas Spmarket';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Americanas Penha';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Americanas Tatuape';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Americanas Jardim Ibitirama';
update public.tm_stores set city=coalesce(nullif(city,''), 'Osasco'), region=coalesce(nullif(region,''), 'Grande SP') where name='Carrefour Osasco';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Norte') where name='Carrefour Bairro do Limão';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Carrefour Aricanduva';
update public.tm_stores set city=coalesce(nullif(city,''), 'Guarulhos'), region=coalesce(nullif(region,''), 'Grande SP') where name='Carrefout Guarulhos';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Carrefour Tatuapé';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Leste') where name='Carrefour Itaquera';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Sul') where name='Carrefour Chácara Santo Antonio';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Sul') where name='Carrefour Santo Amaro';
update public.tm_stores set city=coalesce(nullif(city,''), 'São Paulo'), region=coalesce(nullif(region,''), 'Oeste') where name='Carrefour Pinheiros';
update public.tm_stores set city=coalesce(nullif(city,''), 'Taboão da Serra'), region=coalesce(nullif(region,''), 'Grande SP') where name='Carrfour Taboão da Serra';
update public.tm_stores set city=coalesce(nullif(city,''), 'Barueri'), region=coalesce(nullif(region,''), 'Grande SP') where name='Carrefour Barueri';
