-- Cardoso Hub — FICHA TECNICA 2026 (arquivo -2), carga para a tabela de apoio.
-- Parte 3 de 4. Depende da 0090. Idempotente (on conflict do update).
-- So escreve em public.ficha_2026_stage. Nada de products aqui: quem aplica e a 0092.

insert into public.ficha_2026_stage (ref,cadastro,nome_antigo,nome_embalagem,sub_categoria,nome_tecnico,idade,ean,categoria,linha,marca) values
('6011','Totokinha Sport Azul Caixa Individual','Totokinha Sport Azul Caixa Individual','Totokinha Sport','Primeiros Passos','','+ 18 meses','789648416011-7','Montaria','PLAY&RIDE','PLAYMI'),
('6012','Totokinha Pocoyo com Boneco Caixa Individual','Totokinha Pocoyo com Boneco Caixa Individual','Totokinha Pocoyo com Boneco','Primeiros Passos e Montaria','','+ 18 meses','789648416012-4','Personagens','PLAY&COLLECT','PLAYMI'),
('6013','Totokinha Elly com Boneco Caixa Individual','Totokinha Elly com Boneco Caixa Individual','Totokinha Elly com Boneco','Primeiros Passos e Montaria','','+ 18 meses','789648416013-1','Personagens','PLAY&COLLECT','PLAYMI'),
('6017','Totokinha Disney Ariel Caixa Individual','Totokinha Disney Ariel Caixa Individual','Totokinha','Primeiros Passos e Montaria','','+ 18 meses','789648416017-9','Personagens','PLAY&COLLECT','PLAYMI'),
('6018','Totokinha Marvel Spidey Caixa Individual','Totokinha Marvel Spidey Caixa Individual','Totokinha','Primeiros Passos e Montaria','','+ 18 meses','789648416018-6','Personagens','PLAY&COLLECT','PLAYMI'),
('6019','Totokinha Galinha Pintadinha Mini Caixa Individual','Totokinha Galinha Pintadinha Mini Caixa Individual','Totokinha Galinha Pintadinha Mini','Primeiros Passos e Montaria','','+ 18 meses','789648416019-3','Personagens','PLAY&COLLECT','PLAYMI'),
('6020','Totokinha Bluey Caixa Individual','Lançamento 2026','Totokinha','Primeiros Passos e Montaria','','+ 18 meses','789648416020-9','Personagens','PLAY&COLLECT','PLAYMI'),
('6021','Totokinha Disney Princesas Caixa Individual','Lançamento 2026','Totokinha','Primeiros Passos','','+ 18 meses','789648416021-6','Personagens','PLAY&COLLECT','PLAYMI'),
('7001','Boliche','Boliche','Boliche','Jogos','','+ 3 Anos','789648417001-7','JOGOS','','TÓPI'),
('7101','Elefante Musical Azul','Baby Land Elefante Musical Azul','Elefante Musical','Didáticos eletrônico','BABY LAND ELEFANTE MUSICAL AZUL (teclado musical com luzes)','+ 12 meses','789648417101-4','PRIMEIRA INFÂNCIA','','TÓPI'),
('7102','Elefante Musical Rosa','Baby Land Elefante Musical Rosa','Elefante Musical','Didáticos eletrônico','BABY LAND ELEFANTE MUSICAL ROSA  (teclado musical com luzes)','+ 12 meses','789648417102-1','PRIMEIRA INFÂNCIA','','TÓPI'),
('7103','Girafa Musical','Baby Land Girafa Musical','Girafa Musical','Didáticos eletrônico','BABY LAND GIRAFA MUSICAL  (guitarra musical com luzes)','+ 18 meses','789648417103-8','PRIMEIRA INFÂNCIA','','TÓPI'),
('7104','Macaco Musical','Baby Land Macaco Musical','Macaco Musical','Didáticos eletrônico','BABY LAND MACACO MUSICAL  (teclado musical com luzes)','+ 12 meses','789648417104-5','PRIMEIRA INFÂNCIA','','TÓPI'),
('7105','Pocotó Musical Laranja','Baby Land Pocotó Musical Laranja','Pocotó Musical','Didáticos eletrônico','BABY LAND POCOTÓ MUSICAL LARANJA (cavalo didático de plástico)','+ 18 meses','789648417105-2','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7106','Pocotó Musical Rosa','Baby Land Pocotó Musical Rosa','Pocotó Musical','Didáticos eletrônico','BABY LAND POCOTÓ MUSICAL ROSA  (cavalo didático de plástico)','+ 18 meses','789648417106-9','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7107','Polvo Musical Azul','Baby Land Polvo Musical Azul','Polvo Musical','Didáticos eletrônico','BABY LAND POLVO MUSICAL AZUL  (polvo didático de plástico)','+ 18 meses','789648417107-6','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7108','Polvo Musical Rosa','Baby Land Polvo Musical Rosa','Polvo Musical Rosa','Didáticos eletrônico','BABY LAND POLVO MUSICAL ROSA  (polvo didático de plástico)','+ 18 meses','789648417108-3','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7109','Sapo Musical','Baby Land Sapo Musical','Sapo Musical','Didáticos eletrônico','BABY LAND SAPO MUSICAL (sappo musical didático de plástico)','+ 18 meses','789648417109-0','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7110','Tucano Musical','Baby Land Tucano Musical','Tucano Musical','Didáticos eletrônico','BABY LAND TUCANO MUSICAL  (teclado musical com luzes)','+ 12 meses','789648417110-6','PRIMEIRA INFÂNCIA','','TÓPI'),
('7111','Mesinha de Atividades Musical','Baby Land Mesinha de Atividades Musical','Mesinha de Atividades Musical','Didáticos eletrônico','BABY LAND MESINHA DE ATIVIDADES MUSICAL (mesa didática de plástico com som)','+ 18 meses','789648417111-3','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7112','Carrinho Educativo Azul','Baby Land Carrinho Educativo Azul','Carrinho Educativo','Didáticos eletrônico','BABY LAND CARRINHO EDUCATIVO AZUL (carrinho didático de plástico)','+ 18 meses','789648417112-0','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7113','Carrinho Educativo Rosa','Baby Land Carrinho Educativo Rosa','Carrinho Educativo','Didáticos eletrônico','BABY LAND CARRINHO EDUCATIVO ROSA (carrinho didático de plástico)','+ 18 meses','789648417113-7','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7114','Carro de Bombeiro Musical','Baby Land Carro de Bombeiro Musical','Carro de Bombeiro Musical','Didáticos eletrônico','BABY LAND CARRO DE BOMBEIRO MUSICAL (carrinho didático de plástico)','+ 12 meses','789648417114-4','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7115','Carro de Policia Musical','Baby Land Carro de Policia Musical','Carro de Policia Musical','Didáticos eletrônico','BABY LAND CARRO DE POLICIA MUSICAL (carrinho didático de plástico)','+ 12 meses','789648417115-1','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7116','Ônibus Escolar Musical','Baby Land Ônibus Escolar Musical','Ônibus Escolar Musical','Didáticos eletrônico','BABY LAND ÔNIBUS ESCOLAR MUSICAL (carrinho didático de plástico)','+ 12 meses','789648417116-8','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7117','Pick- Up Super Fast','Baby Land Pick- Up Super Fast','Pick- Up Super Fast','Didáticos eletrônico','','+ 18 meses','789648417117-5','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7118','Carrinho Super Fast','Baby Land Carrinho Super Fast','Carrinho Super Fast','Didáticos eletrônico','','+ 18 meses','789648417118-2','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7119','Kombinha Super Fast','Baby Land Kombinha Super Fast','Kombinha Super Fast','Didáticos eletrônico','','+ 18 meses','789648417119-9','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7120','Pet Home com Blocos Azul','Baby Land Pet Home com Blocos Azul','Pet Home','Didáticos','','+ 3 Anos','789648417120-5','PRIMEIRA INFÂNCIA','','TÓPI'),
('7121','Pet Home com Blocos Rosa','Baby Land Pet Home com Blocos Rosa','Pet Home','Didáticos','','+ 3 Anos','789648417121-2','PRIMEIRA INFÂNCIA','','TÓPI'),
('7122','Doce Cozinha Plus Comidinha','Doce Cozinha Plus Comidinha','Doce Cozinha Plus Comidinha','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648417122-9','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('7123','Doce Cozinha Plus Liquidificador','Doce Cozinha Plus Liquidificador','Doce Cozinha Plus Liquidificador','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648417123-6','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('7124','Doce Cozinha Plus Microondas e Batedeira','Doce Cozinha Plus Microondas e Batedeira','Doce Cozinha Plus Microondas e Batedeira','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648417124-3','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('7125','Doce Cozinha Plus Torradeira e Batedeira','Doce Cozinha Plus Torradeira e Batedeira','Doce Cozinha Plus Torradeira e Batedeira','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648417125-0','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('7126','Pet Club Hora do Banho','Pet Club Hora do Banho','Pet Club Hora do Banho','Pets, kits e acessórios','','+ 3 Anos','789648417126-7','FAZ DE CONTA','','TÓPI'),
('7127','Pet Club Hora do Passeio','Pet Club Hora do Passeio','Pet Club Hora do Passeio','Pets, kits e acessórios','','+ 3 Anos','789648417127-4','FAZ DE CONTA','','TÓPI'),
('7128','Pet Club Hora do Soninho','Pet Club Hora do Soninho','Pet Club Hora do Soninho','Pets, kits e acessórios','','+ 3 Anos','789648417128-1','FAZ DE CONTA','','TÓPI'),
('7129','Dinocar com Carrinhos','Dinocar com Carrinhos','Dinocar','Caminhões Roda Livre','','+ 3 Anos','789648417129-8','RODA LIVRE','','TÓPI'),
('7130','City Driver Amarelo','City Driver Amarelo','City Driver','Ônibus Roda Livre','','+ 3 Anos','789648417130-4','RODA LIVRE','','TÓPI'),
('7131','City Driver Vermelho','City Driver Vermelho','City Driver','Ônibus Roda Livre','','+ 3 Anos','789648417131-1','RODA LIVRE','','TÓPI'),
('7132','City Truck Bombeiro','City Truck Bombeiro','City Truck Bombeiro','Caminhões Roda Livre','','+ 3 Anos','789648417132-8','RODA LIVRE','','TÓPI'),
('7133','City Truck Construção','City Truck Construção','City Truck Construção','Caminhões Roda Livre','','+ 3 Anos','789648417133-5','RODA LIVRE','','TÓPI'),
('7134','City Truck Reciclagem','City Truck Reciclagem','City Truck Reciclagem','Caminhões Roda Livre','','+ 3 Anos','789648417134-2','RODA LIVRE','','TÓPI'),
('7135','Corrida Radical 360°','Corrida Radical 360°','Corrida Radical 360°','Pista de carros','','+ 3 Anos','789648417135-9','RODA LIVRE','','TÓPI'),
('7136','Corrida Radical 360° com 2 Loopings','Corrida Radical 360° com 2 Loopings','Corrida Radical 360° com 2 Loopings','Pista de carros','','+ 3 Anos','789648417136-6','RODA LIVRE','','TÓPI'),
('7137','Corrida Radical Dinossauro','Corrida Radical Dinossauro','Corrida Radical Dinossauro','Pista de carros','','+ 3 Anos','789648417137-3','RODA LIVRE','','TÓPI'),
('7138','Estação de Bombeiro','Estação de Bombeiro','Estação de Bombeiro','Estação','','+ 3 Anos','789648417138-0','Roda Livre','PLAY&DRIVE','PLAYMI'),
('7139','Estação de Bombeiro Plus','Estação de Bombeiro Plus','Estação de Bombeiro Plus','Estação','','+ 3 Anos','789648417139-7','Roda Livre','PLAY&DRIVE','PLAYMI'),
('7140','Estação de Construção','Estação de Construção','Estação de Construção','Estação','','+ 3 Anos','789648417140-3','Roda Livre','PLAY&DRIVE','PLAYMI'),
('7141','Estação de Reciclagem','Estação de Reciclagem','Estação de Reciclagem','Estação','','+ 3 Anos','789648417141-0','Roda Livre','PLAY&DRIVE','PLAYMI'),
('7142','City Rescue Ambulância','City Rescue Ambulância','City Rescue Ambulância','Caminhões Roda Livre','','+ 3 Anos','789648417142-7','RODA LIVRE','','TÓPI'),
('7143','City Rescue Bombeiro','City Rescue Bombeiro','City Rescue Bombeiro','Caminhões Roda Livre','','+ 3 Anos','789648417143-4','RODA LIVRE','','TÓPI'),
('7144','City Rescue Policia','City Rescue Policia','City Rescue Policia','Caminhões Roda Livre','','+ 3 Anos','789648417144-1','RODA LIVRE','','TÓPI'),
('7148','Dinocar Com Acessórios','Dinocar Com Acessórios','Dinocar Com Acessórios','Caminhões Roda Livre','','+ 3 Anos','789648417148-9','RODA LIVRE','','TÓPI'),
('7149','Soft Car Musical','Baby Land Soft Car Musical','Soft Car Musical','Didáticos eletrônico','','+ 18 Meses','789648417149-6','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7150','Soft Truck Betoneira Musical','Baby Land Soft Truck Betoneira Musical','Soft Truck Betoneira Musical','Didáticos eletrônico','','+ 18 Meses','789648417150-2','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7151','Soft Truck Caçamba Musical','Baby Land Soft Truck Caçamba Musical','Soft Truck Caçamba Musical','Didáticos eletrônico','','+ 18 Meses','789648417451-9','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7152','Soft Truck Reboque Musical','Baby Land Soft Truck Reboque Musical','Soft Truck Reboque Musical','Didáticos eletrônico','','+ 18 Meses','789648417452-6','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7153','Dino Betoneira Musical','Baby Land Dino Betoneira Musical','Dino Betoneira Musical','Didáticos eletrônico','','+ 12 Meses','789648417153-3','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7154','Dino Caçamba Musical','Baby Land Dino Caçamba Musical','Dino Caçamba Musical','Didáticos eletrônico','','+ 12 Meses','789648417154-0','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7155','Dino Ecológico Musical','Baby Land Dino Ecológico Musical','Dino Ecológico Musical','Didáticos eletrônico','','+ 12 meses','789648417155-7','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7156','Dino Escavadeira Musical','Baby Land Dino Escavadeira Musical','Dino Escavadeira Musical','Didáticos eletrônico','','+ 12 Meses','789648417156-4','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7157','Bi-Bi Blum Didático','Baby Land Bi-Bi Blum Didático','Bi-Bi Blum Didático','Didáticos eletrônico','','+ 18 Meses','789648417157-1','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7158','Dino Ritmo Divertido','Baby Land Dino Ritmo Divertido','Dino Ritmo Divertido','Didáticos eletrônico','','+ 18 Meses','789648417158-8','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7159','Bateria Show Musical Azul','Baby Land Bateria Show Musical Azul','Bateria Show Musical','Didáticos eletrônico','','+ 18 Meses','789648417159-5','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7160','Xilofone Didático','Baby Land Xilofone Didático','Xilofone Didático','Didáticos','','+ 18 Meses','789648417160-1','Primeira Infância','PLAY&LEARN','PLAYMI'),
('7161','Fire Rescue Bombeiro','Fire Rescue Bombeiro','Fire Rescue Bombeiro','Caminhões Roda Livre','','+ 3 Anos','789648417161-8','RODA LIVRE','','TÓPI'),
('7162','Fire Rescue Polícia','Fire Rescue Polícia','Fire Rescue Polícia','Caminhões Roda Livre','','+ 3 Anos','789648417162-5','RODA LIVRE','','TÓPI'),
('7163','Travel Driver Bus Amarelo','Travel Driver Bus Amarelo','Travel Driver Bus Amarelo','Ônibus Roda Livre','','+ 3 Anos','789648417163-2','RODA LIVRE','','TÓPI'),
('7164','Travel Driver Bus Vermelho','Travel Driver Bus Vermelho','Travel Driver Bus Vermelho','Ônibus Roda Livre','','+ 3 Anos','789648417164-9','RODA LIVRE','','TÓPI'),
('7165','T-Rex Relâmpago','T-Rex Relâmpago','T-Rex Relâmpago','Caminhões Roda Livre','','+ 3 Anos','789648417165-6','RODA LIVRE','','TÓPI'),
('7171','Display Robô-Blocks Serviço','Display Robô-Blocks Serviço','Display Robô-Blocks Serviço','Blocos de montar','','+ 3 Anos','789648417171-7','RODA LIVRE','','TÓPI'),
('7172','Robô-Blocks Serviço Varredor - 46 Peças','Robô-Blocks Serviço Varredor - 46 Peças','Robô-Blocks Serviço Varredor','Blocos de montar','','+ 3 Anos','789648417175-5','RODA LIVRE','','TÓPI'),
('7173','Robô-Blocks Serviço Delivery - 45 Peças','Robô-Blocks Serviço Delivery - 45 Peças','Robô-Blocks Serviço Delivery','Blocos de montar','','+ 3 Anos','789648417175-5','RODA LIVRE','','TÓPI'),
('7174','Robô-Blocks Serviço Caminhão Pipa - 45 Peças','Robô-Blocks Serviço Caminhão Pipa - 45 Peças','Robô-Blocks Serviço Caminhão Pipa','Blocos de montar','','+ 3 Anos','789648417175-5','RODA LIVRE','','TÓPI'),
('7175','Robô-Blocks Serviço Ambulãncia- 47 Peças','Robô-Blocks Serviço Ambulãncia- 47 Peças','Robô-Blocks Serviço Ambulãncia','Blocos de montar','','+ 3 Anos','789648417175-5','RODA LIVRE','','TÓPI'),
('7176','Display Robô-Blocks Corrida','Display Robô-Blocks Corrida','Display Robô-Blocks Corrida','','','+ 3 Anos','789648417176-2','RODA LIVRE','','TÓPI'),
('7177','Robô-Blocks Corrida F-Car-53 Peças','Robô-Blocks Corrida F-Car-53 Peças','Robô-Blocks Corrida F-Car','Blocos de montar','','+ 3 Anos','789648417177-9','RODA LIVRE','','TÓPI'),
('7178','Robô-Blocks Corrida F-Road - 59 Peças','Robô-Blocks Corrida F-Road - 59 Peças','Robô-Blocks Corrida F-Road','Blocos de montar','','+ 3 Anos','789648417178-6','RODA LIVRE','','TÓPI'),
('7179','Robô-Blocks Corrida F- Quadri - 42 Peças','Robô-Blocks Corrida F- Quadri - 42 Peças','Robô-Blocks Corrida F- Quadri','Blocos de montar','','+ 3 Anos','789648417179-3','RODA LIVRE','','TÓPI')
on conflict (ref) do update set cadastro=excluded.cadastro, nome_antigo=excluded.nome_antigo, nome_embalagem=excluded.nome_embalagem, sub_categoria=excluded.sub_categoria, nome_tecnico=excluded.nome_tecnico, idade=excluded.idade, ean=excluded.ean, categoria=excluded.categoria, linha=excluded.linha, marca=excluded.marca;