-- Cardoso Hub — FICHA TECNICA 2026 (arquivo -2), carga para a tabela de apoio.
-- Parte 1 de 4. Depende da 0090. Idempotente (on conflict do update).
-- So escreve em public.ficha_2026_stage. Nada de products aqui: quem aplica e a 0092.

insert into public.ficha_2026_stage (ref,cadastro,nome_antigo,nome_embalagem,sub_categoria,nome_tecnico,idade,ean,categoria,linha,marca) values
('71','Tandy Caçamba (Na Rede)','Tandy Caçamba (Sem Embalagem)','Tandy Caçamba','Caminhões Roda Livre','','+ 3 Anos','789648410071-7','RODA LIVRE','','TÓPI'),
('72','Tandy Tractor (Na Rede)','Tandy Tractor (Sem Embalagem)','Tandy Tractor','Caminhões Roda Livre','','+ 3 Anos','789648410072-4','RODA LIVRE','','TÓPI'),
('78','Tandy Bombeiro (Na Rede)','Tandy Bombeiro (Sem Embalagem)','Tandy Bombeiro','Caminhões Roda Livre','','+ 3 Anos','789648410078-6','RODA LIVRE','','TÓPI'),
('124','Leva Papinha','Sweet Fantasy Leva-Papinha','Leva Papinha','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648410124-0','FAZ DE CONTA','','TÓPI'),
('125','Carrinho de Boneca Passeio do Bebê','Carrinho de Boneca Passeio do Bebê','Carrinho de Boneca Passeio do Bebê','Bonecas e Acessórios','','+ 3 Anos','789648410125-7','FAZ DE CONTA','','TÓPI'),
('133','Mini Mercado','Sweet Fantasy Mini-Mercado','Mini Mercado','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648410133-2','FAZ DE CONTA','','TÓPI'),
('205','Baldão de Praia','Baldão de Praia','Baldão de Praia','Linha Praia','','+ 3 Anos','789648410205-6','AR LIVRE','','TÓPI'),
('209','Baldico de Praia','Baldico de Praia','Baldico de Praia','Linha Praia','','+ 18 meses','789648410209-4','AR LIVRE','','TÓPI'),
('263','Tambor Pocoyo','Tambor Pocoyo','Tambor','Instrumentos Musicais','','+ 3 Anos','789648410263-6','Personagens','PLAY&COLLECT','PLAYMI'),
('266','Tamborete Pocoyo','Tamborete Pocoyo','Tamborete','Instrumentos Musicais','','+ 3 Anos','789648410266-7','Personagens','PLAY&COLLECT','PLAYMI'),
('272','Guitarra Pocoyo','Guitarra Pocoyo','Guitarra','Instrumentos Musicais','','+ 4 anos','789648410272-8','Personagens','PLAY&COLLECT','PLAYMI'),
('275','Boneco de Vinil Pocoyo','Boneco de Vinil Pocoyo','Boneco de Vinil','Vínil','','+ 18 meses','789648410275-9','Personagens','PLAY&COLLECT','PLAYMI'),
('280','Mipuxa Azul','Baby Land Mipuxa Azul','Mipuxa','Didáticos','BABY LAND MIPUXA AZUL (carrinho de puxar de plástico)','+ 18 meses','789648410280-3','PRIMEIRA INFÂNCIA','','TÓPI'),
('281','Boneco de Vinil Loula','Boneco de Vinil Loula','Boneco de Vinil','Vínil','','+ 18 meses','789648410281-0','Personagens','PLAY&COLLECT','PLAYMI'),
('282','Boneco de Vinil Pato','Boneco de Vinil Pato','Boneco de Vinil','Vínil','','+ 18 meses','789648410282-7','Personagens','PLAY&COLLECT','PLAYMI'),
('300','Totokinha Clássica Rosa Caixa Individual','Totokinha Clássica Rosa Caixa Individual','Totokinha Clássica','Primeiros Passos','','+ 18 meses','789648410300-8','Montaria','PLAY&RIDE','PLAYMI'),
('301','Totokinha Clássica Azul Caixa Individual','Totokinha Clássica Azul Caixa Individual','Totokinha Clássica','Primeiros Passos','','+ 18 meses','789648410301-5','Montaria','PLAY&RIDE','PLAYMI'),
('1007','Dino Sabidinho','Baby Land Dino Sabidinho','Dino Sabidinho','Caminhões Didáticos','BABY LAND DINO SABIDINHO (carrinho didático de plástico)','+ 18 meses','789648411007-5','PRIMEIRA INFÂNCIA','','TÓPI'),
('1017','Tandy Tractor','Tandy Tractor','Tandy Tractor','Caminhões Roda Livre','','+ 3 Anos','789648411017-4','Roda Livre','PLAY&DRIVE','PLAYMI'),
('1018','Combo 2 Construction','Combo 2 Construction','Combo 2 Construction','Caminhões Roda Livre','','+ 3 Anos','789648411018-1','Roda Livre','PLAY&DRIVE','PLAYMI'),
('1036','Jeep Rally (No Filme)','Jeep Rally (Sem Embalagem)','Jeep Rally','Jipes Roda Livre','','+ 3 Anos','789648411036-5','RODA LIVRE','','TÓPI'),
('1040','Combo Trator Escavadeira','Combo Trator Escavadeira','Combo Trator Escavadeira','Tratores','','+ 3 Anos','789648411040-2','RODA LIVRE','','TÓPI'),
('1041','Combo Trator Retroescavadeira','Combo Trator Retroescavadeira','Combo Trator Retroescavadeira','Tratores','','+ 3 Anos','789648411041-9','RODA LIVRE','','TÓPI'),
('1042','Invictus Basculante','Invictus Basculante','Invictus Basculante','Tratores','','+ 3 Anos','789648411042-6','RODA LIVRE','','TÓPI'),
('1044','Invictus Graneleiro','Invictus Graneleiro','Invictus Graneleiro','Caminhões Roda Livre','','+ 3 Anos','789648411044-0','RODA LIVRE','','TÓPI'),
('1045','Invictus Resgate','Invictus Resgate','Invictus Resgate','Caminhões Roda Livre','','+ 3 Anos','789648411045-7','RODA LIVRE','','TÓPI'),
('1046','Jeep Rally','Jeep Rally (Carrinho De Plástico)','Jeep Rally','Jipes Roda Livre','','+ 3 Anos','789648411046-4','RODA LIVRE','','TÓPI'),
('1049','Tandy Bombeiro','Tandy Bombeiro','Tandy Bombeiro','Caminhões Roda Livre','','+ 3 Anos','789648411049-5','Roda Livre','PLAY&DRIVE','PLAYMI'),
('1051','Combo Agro Trator','Combo Agro Trator','Combo Agro Trator','Caminhões Roda Livre','','+ 3 Anos','789648411051-8','RODA LIVRE','','TÓPI'),
('1052','Dino Praia','Dino Praia','Dino Praia','Linha Praia','','+ 18 meses','789648411052-5','AR LIVRE','','TÓPI'),
('1053','Invictus Sky','Invictus Sky','Invictus Sky','Caminhões Roda Livre','','+ 3 Anos','789648411053-2','RODA LIVRE','','TÓPI'),
('1058','Invictus Super Cegonheiro','Invictus Super Cegonheiro','Invictus Super Cegonheiro','Caminhões Roda Livre','','+ 3 Anos','789648411058-7','RODA LIVRE','','TÓPI'),
('1059','Open Tracks Trator Retroescavadeira','Open Tracks Trator Retroescavadeira','Open Tracks Trator Retroescavadeira','Caminhões Roda Livre','','+ 3 Anos','789648411059-4','Roda Livre','PLAY&DRIVE','PLAYMI'),
('1060','Open Tracks Trator Escavadeira','Open Tracks Trator Escavadeira','Open Tracks Trator Escavadeira','Caminhões Roda Livre','','+ 3 Anos','789648411060-0','Roda Livre','PLAY&DRIVE','PLAYMI'),
('1061','Open Tracks Trator Carregadeira','Open Tracks Trator Carregadeira','Open Tracks Trator Carregadeira','Caminhões Roda Livre','','+ 3 Anos','789648411061-7','Roda Livre','PLAY&DRIVE','PLAYMI'),
('1062','Caminhão Air Truck Caçamba','Caminhão Air Truck Caçamba','Caminhão Air Truck Caçamba','Caminhões Roda Livre','','+ 3 Anos','789648411062-4','Roda Livre','PLAY&DRIVE','PLAYMI'),
('1063','Caminho  Air Truck Escavadeira','Caminho  Air Truck Escavadeira','Caminho  Air Truck Escavadeira','Caminhões Roda Livre','','+ 3 Anos','789648411063-1','Roda Livre','PLAY&DRIVE','PLAYMI'),
('2001','Carrinho de Boneca Meu Nenê','Carrinho de Boneca Meu Nenê','Carrinho de Boneca Meu Nenê','Bonecas e Acessórios','','+ 3 Anos','789648412001-2','FAZ DE CONTA','','TÓPI'),
('2003','Carrinho de Boneca Desmontado','Carrinho de Boneca Desmontado','Carrinho de Boneca','Bonecas e Acessórios','','+ 3 Anos','789648412003-6','FAZ DE CONTA','','TÓPI'),
('2004','Doce Cozinha Almocinho','Doce Cozinha Almocinho','Doce Cozinha Almocinho','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412004-3','FAZ DE CONTA','','TÓPI'),
('2005','Doce Cozinha Lanchinho','Doce Cozinha Lanchinho','Doce Cozinha Lanchinho','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412005-0','FAZ DE CONTA','','TÓPI'),
('2006','Doce Cozinha Jantinha','Doce Cozinha Jantinha','Doce Cozinha Jantinha','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412006-7','FAZ DE CONTA','','TÓPI'),
('2009','Carrinho de Boneca Desmontado','Carrinho de Boneca Desmontado','Carrinho de Boneca','Bonecas e Acessórios','','+ 3 Anos','789648412009-8','FAZ DE CONTA','','TÓPI'),
('2010','Doce Cozinha Faz de Conta','Doce Cozinha Faz de Conta','Doce Cozinha Faz de Conta','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412010-4','FAZ DE CONTA','','TÓPI'),
('2011','Doce Cozinha Fogãozinho','Doce Cozinha Fogãozinho','Doce Cozinha Fogãozinho','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412011-1','FAZ DE CONTA','','TÓPI'),
('2012','Geladeira Sonho de Menina','Sweet Fantasy Geladeira Sonho de Menina','Geladeira Sonho de Menina','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412012-8','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('2013','Cozinha Sonho de Menina','Sweet Fantasy Cozinha Sonho de Menina','Cozinha Sonho de Menina','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412013-5','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('2014','Geladeira Gela Sorvetinho','Sweet Fantasy Geladeira Gela Sorvetinho','Geladeira Gela Sorvetinho','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412014-2','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('2015','Geladeira Sonho de Menina Caixa Individual','Sweet Fantasy Geladeira Sonho de Menina Caixa Individual','Geladeira Sonho de Menina','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412015-9','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('2016','Cozinha Sonho de Menina Caixa Individual','Sweet Fantasy Cozinha Sonho de Menina Caixa Individual','Cozinha Sonho de Menina','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412016-6','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('2017','Geladeira Gela Sorvetinho Caixa Individual','Sweet Fantasy Geladeira Gela Sorvetinho Caixa Individual','Geladeira Gela Sorvetinho','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412017-3','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('2018','Acqua Bubble','Acqua Bubble','Acqua Bubble','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412018-0','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('2019','Acqua Bubble Caixa Individual','Acqua Bubble Caixa Individual','Acqua Bubble','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412019-7','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('2020','Doce Cozinha Gourmet Air Fryer','Doce Cozinha Gourmet Air Fryer','Doce Cozinha Gourmet Air Fryer','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412020-3','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('2021','Doce Cozinha Gourmet Batedeira','Doce Cozinha Gourmet Batedeira','Doce Cozinha Gourmet Batedeira','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412021-0','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('2022','Doce Cozinha Gourmet Liquidificador','Doce Cozinha Gourmet Liquidificador','Doce Cozinha Gourmet Liquidificador','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412022-7','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('2023','Doce Cozinha Gourmet Máquina de Café Espresso','Doce Cozinha Gourmet Máquina de Café Espresso','Doce Cozinha Gourmet Máquina de Café Espresso','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412023-4','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('2024','Doce Cozinha Gourmet Microondas','Doce Cozinha Gourmet Microondas','Doce Cozinha Gourmet Microondas','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648412024-1','Faz de conta','PLAY&IMAGINE','PLAYMI'),
('3007','Teltaluga','Baby Land Teltaluga','Teltaluga','Didáticos','BABY LAND TELTALUGA (tartaruga didática de plástico com telefone)','+ 18 meses','789648413007-3','PRIMEIRA INFÂNCIA','','TÓPI'),
('3008','Tortuga','Baby Land Tortuga','Tortuga','Didáticos','BABY LAND TORTUGA (tartaruga didática de plástico)','+ 18 meses','789648413008-0','PRIMEIRA INFÂNCIA','','TÓPI'),
('3011','Boneco de Vinil Elly','Boneco de Vinil Elly','Boneco de Vinil','Vínil','','+ 18 meses','789648413011-0','Personagens','PLAY&COLLECT','PLAYMI'),
('3012','Pata Bota-Ovo','Baby Land Pata Bota-Ovo','Pata Bota-Ovo','Didáticos','BABY LAND PATA BOTA-OVO (pato didático de plástico)','+ 18 meses','789648413012-7','PRIMEIRA INFÂNCIA','','TÓPI'),
('3013','Miniaturas Pocoyo','Miniaturas Pocoyo','Boneco de Vinil','Vínil','','+ 3 anos','789648413013-4','Personagens','PLAY&COLLECT','PLAYMI'),
('3021','Boneco de Vinil Nina','Boneco de Vinil Nina','Boneco de Vinil','Vínil','','+ 18 meses','789648413021-9','Personagens','PLAY&COLLECT','PLAYMI'),
('3027','Dino Bombeirinho','Baby Land Dino Bombeirinho','Dino Bombeirinho','Didáticos','BABY LAND DINO BOMBEIRINHO (carrinho didático de plástico)','+ 18 meses','789648413027-1','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3028','Dino Escolar','Baby Land Dino Escolar','Dino Escolar','Didáticos','BABY LAND DINO ESCOLAR (carrinho didático de plástico)','+ 18 meses','789648413028-8','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3029','Dino Sabidinho Plus','Baby Land Dino Sabidinho Plus','Dino Sabidinho Plus','Didáticos','BABY LAND DINO SABIDINHO PLUS (carrinho didático de plástico)','+ 18 meses','789648413029-5','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3033','Totokinha Bolinha Rosa','Totokinha Bolinha Rosa','Totokinha Bolinha','Primeiros Passos','','+ 18 meses','789648413033-2','Montaria','PLAY&RIDE','PLAYMI'),
('3034','Totokinha Bolinha Azul','Totokinha Bolinha Azul','Totokinha Bolinha','Primeiros Passos','','+ 18 meses','789648413034-9','Montaria','PLAY&RIDE','PLAYMI'),
('3038','Miniaturas Galinha Pintadinha','Miniaturas Galinha Pintadinha','Miniaturas Galinha Pintadinha','Vínil','','+ 3 anos','789648413038-7','Personagens','PLAY&COLLECT','PLAYMI'),
('3045','Totoka Plus sem Eletrônico Rosa','Totoka Plus sem Eletrônico Rosa','Totoka Plus','Primeiros Passos','','+ 18 meses','789648413045-5','Montaria','PLAY&RIDE','PLAYMI'),
('3046','Totoka Plus sem Eletrônico Azul','Totoka Plus sem Eletrônico Azul','Totoka Plus','Primeiros Passos','','+ 18 meses','789648413046-2','Montaria','PLAY&RIDE','PLAYMI'),
('3048','Boneco de Vinil Fred','Boneco de Vinil Fred','Boneco de Vinil','Vínil','','+ 18 meses','789648413048-6','Personagens','PLAY&COLLECT','PLAYMI'),
('3049','Boneco de Vinil Sonequita','Boneco de Vinil Sonequita','Boneco de Vinil','Vínil','','+ 18 meses','789648413049-3','Personagens','PLAY&COLLECT','PLAYMI'),
('3050','Boneco de Vinil Pocoyo Grande','Boneco de Vinil Pocoyo Grande','Boneco de Vinil','Vínil','','+ 18 meses','789648413050-9','Personagens','PLAY&COLLECT','PLAYMI'),
('3051','Boneco de Vinil Elly Grande','Boneco de Vinil Elly Grande','Boneco de Vinil','Vínil','','+ 18 meses','789648413051-6','Personagens','PLAY&COLLECT','PLAYMI'),
('3052','Boneco de Vinil Pato Grande','Boneco de Vinil Pato Grande','Boneco de Vinil','Vínil','','+ 18 meses','798648413052-3','Personagens','PLAY&COLLECT','PLAYMI'),
('3053','Mesinha de Atividades Rosa Caixa Individual','Baby Land Mesinha de Atividades Rosa Caixa Individual','Mesinha de Atividades','Didáticos','BABY LAND MESINHA DE ATIVIDADES ROSA CAIXA INDIVIDUAL (mesa didática de plástico)','+ 18 meses','789648413053-0','PRIMEIRA INFÂNCIA','','TÓPI'),
('3054','Mesinha de Atividades Azul Caixa Indivudual','Baby Land Mesinha de Atividades Azul Caixa Indivudual','Mesinha de Atividades','Didáticos','BABY LAND MESINHA DE ATIVIDADES AZUL CAIXA INDIVUDUAL (mesa didática de plástico)','+ 18 meses','789648413054-7','PRIMEIRA INFÂNCIA','','TÓPI'),
('3055','Bauduxo Didatico Rosa sem Embalagem','Baby Land Bauduxo Didatico Rosa sem Embalagem','Bauduxo Didatico','Didáticos','BABY LAND BAUDUXO DIDATICO ROSA SEM EMBALAGEM (baú dIdático de plástico com rodas)','+ 18 meses','789648413055-4','PRIMEIRA INFÂNCIA','','TÓPI')
on conflict (ref) do update set cadastro=excluded.cadastro, nome_antigo=excluded.nome_antigo, nome_embalagem=excluded.nome_embalagem, sub_categoria=excluded.sub_categoria, nome_tecnico=excluded.nome_tecnico, idade=excluded.idade, ean=excluded.ean, categoria=excluded.categoria, linha=excluded.linha, marca=excluded.marca;