-- Cardoso Hub — FICHA TECNICA 2026 (arquivo -2), carga para a tabela de apoio.
-- Parte 2 de 4. Depende da 0090. Idempotente (on conflict do update).
-- So escreve em public.ficha_2026_stage. Nada de products aqui: quem aplica e a 0092.

insert into public.ficha_2026_stage (ref,cadastro,nome_antigo,nome_embalagem,sub_categoria,nome_tecnico,idade,ean,categoria,linha,marca) values
('3056','Bauduxo Didatico Azul sem Embalagem','Baby Land Bauduxo Didatico Azul sem Embalagem','Bauduxo Didatico','Didáticos','BABY LAND BAUDUXO DIDATICO AZUL SEM EMBALAGEM (baú dIdático de plástico com rodas)','+ 18 meses','789648413056-1','PRIMEIRA INFÂNCIA','','TÓPI'),
('3057','Tópi Bombeirinho','Tópi Bombeirinho (Carrinho Didático de Plástico)','Bombeirinho','Didáticos','','+ 18 meses','789648413057-8','PRIMEIRA INFÂNCIA','','TÓPI'),
('3058','Tópi Escolar','Tópi Escolar (Carrinho Didático de Plástico)','Escolar','Didáticos','','+ 18 meses','789648413058-5','PRIMEIRA INFÂNCIA','','TÓPI'),
('3059','Tópi Sabidinho Plus','Tópi Sabidinho Plus (Carrinho Didático de Plástico)','Sabidinho Plus','Didáticos','','+ 18 meses','789648413059-2','PRIMEIRA INFÂNCIA','','TÓPI'),
('3063','Totokinha Pocoyo com Boneco','Totokinha Pocoyo com Boneco','Totokinha Pocoyo com Boneco','Primeiros Passos e Montaria','','+ 18 meses','789648413063-9','Personagens','PLAY&COLLECT','PLAYMI'),
('3064','Boneco de Pelúcia Pocoyo','Boneco de Pelúcia Pocoyo','Boneco de Pelúcia','Pelúcia','','+ 2 meses','789648413064-6','Personagens','PLAY&COLLECT','PLAYMI'),
('3065','Boneco de Pelúcia e Vinil Pocoyo','Boneco de Pelúcia e Vinil Pocoyo','Boneco de Pelúcia e Vinil','Pelúcia e vinil','','+ 12 meses','789648413065-3','Personagens','PLAY&COLLECT','PLAYMI'),
('3066','Totokinha Sport Rosa','Totokinha Sport Rosa','Totokinha Sport','Primeiros Passos','','+ 18 meses','789648413066-0','Montaria','PLAY&RIDE','PLAYMI'),
('3067','Totokinha Sport Azul','Totokinha Sport Azul','Totokinha Sport','Primeiros Passos','','+ 18 meses','789648413067-7','Montaria','PLAY&RIDE','PLAYMI'),
('3068','Totokinha Elly com Boneco','Totokinha Elly com Boneco','Totokinha Elly com Boneco','Primeiros Passos e Montaria','','+ 18 meses','789648413068-4','Personagens','PLAY&COLLECT','PLAYMI'),
('3078','Mipuxa Rosa','Baby Land Mipuxa Rosa','Mipuxa','Didáticos','BABY LAND MIPUXA ROSA (carrinho de puxar de plástico)','+ 18 meses','789648413078-3','PRIMEIRA INFÂNCIA','','TÓPI'),
('3079','Boneco de Vinil Temático Pocoyo Frankenstein','Boneco de Vinil Temático Pocoyo Frankenstein','Coleção Temática','Vínil','','+ 18 meses','789648413079-0','Personagens','PLAY&COLLECT','PLAYMI'),
('3080','Boneco de Vinil Temático Pocoyo Príncipe','Boneco de Vinil Temático Pocoyo Príncipe','Coleção Temática','Vínil','','+ 18 meses','789648413080-6','Personagens','PLAY&COLLECT','PLAYMI'),
('3081','Boneco de Vinil Temático Pocoyo Super Herói','Boneco de Vinil Temático Pocoyo Super Herói','Coleção Temática','Vínil','','+ 18 meses','789648413081-3','Personagens','PLAY&COLLECT','PLAYMI'),
('3082','Fofilhotes Trenzinho','Baby Land Fofilhotes Trenzinho','Fofilhotes Trenzinho','Didáticos','BABY LAND FOFILHOTES TRENZINHO (trenzinho didático de plástico)','+ 18 meses','789648413082-0','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3083','Fofilhotes Trenzinho com Carretinha','Baby Land Fofilhotes Trenzinho com Carretinha','Fofilhotes Trenzinho com Carretinha','Didáticos','BABY LAND FOFILHOTES TRENZINHO COM CARRETINHA (trenzinho didático de plástico com carreta)','+ 18 meses','789648413083-7','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3084','Fofilhotes Ônibus','Baby Land Fofilhotes Ônibus','Fofilhotes Ônibus','Didáticos','BABY LAND FOFILHOTES ÔNIBUS (ônibus didático de plástico)','+ 18 meses','789648413084-4','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3085','Fofilhotes Ônibus com Carretinha','Baby Land Fofilhotes Ônibus com Carretinha','Fofilhotes Ônibus com Carretinha','Didáticos','BABY LAND FOFILHOTES ÔNIBUS COM CARRETINHA (ônibus didático de plástico com carreta)','+ 18 meses','789648413085-1','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3086','Fofilhotes Jipinho','Baby Land Fofilhotes Jipinho','Fofilhotes Jipinho','Didáticos','BABY LAND FOFILHOTES JIPINHO  (jipe didático de plástico)','+ 18 meses','789648413086-8','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3087','Fofilhotes Jipinho com Carretinha','Baby Land Fofilhotes Jipinho com Carretinha','Fofilhotes Jipinho com Carretinha','Didáticos','BABY LAND FOFILHOTES JIPINHO COM CARRETINHA (jipe didático de plástico com carreta)','+ 18 meses','789648413087-5','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3088','Fofilhotes Tratorzinho','Baby Land Fofilhotes Tratorzinho','Fofilhotes Tratorzinho','Didáticos','BABY LAND FOFILHOTES TRATORZINHO (tratorzinho didático de plástico)','+ 18 meses','789648413088-2','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3089','Fofilhotes Tratorzinho com Carretinha','Baby Land Fofilhotes Tratorzinho com Carretinha','Fofilhotes Tratorzinho com Carretinha','Didáticos','BABY LAND FOFILHOTES TRATORZINHO COM CARRETINHA (tratorzinho didático de plástico com carreta)','+ 18 meses','789648413089-9','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3090','Fofilhotes Cavalinho','Baby Land Fofilhotes Cavalinho','Fofilhotes','Didáticos','BABY LAND FOFILHOTES CAVALINHO (bicho de vinil)','+ 18 meses','789648413090-5','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3091','Fofilhotes Girafinha','Baby Land Fofilhotes Girafinha','Fofilhotes','Didáticos','BABY LAND FOFILHOTES GIRAFINHA (bicho de vinil)','+ 18 meses','789648413091-2','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3092','Fofilhotes Hipopótamo','Baby Land Fofilhotes Hipopótamo','Fofilhotes','Didáticos','BABY LAND FOFILHOTES HIPOPÓTAMOZINHO (bicho de vinil)','+ 18 meses','789648413092-9','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3093','Fofilhotes Leãozinho','Baby Land Fofilhotes Leãozinho','Fofilhotes','Didáticos','BABY LAND FOFILHOTES LEÃOZINHO (bicho de vinil)','+ 18 meses','789648413093-6','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3094','Fofilhotes Tigre','Baby Land Fofilhotes Tigre','Fofilhotes','Didáticos','BABY LAND FOFILHOTES TIGRINHO (bicho de vinil)','+ 18 meses','789648413094-3','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3095','Fofilhotes Hipopótamo Rosa','Baby Land Fofilhotes Hipopótamo Rosa','Fofilhotes','Didáticos','BABY LAND FOFILHOTES HIPOPÓTAMOZINHO (bicho de vinil)','+ 18 meses','789648413095-0','Primeira Infância','PLAY&LEARN','PLAYMI'),
('3096','Totokinha Disney Ariel','Totokinha Disney Ariel','Totokinha','Primeiros Passos e Montaria','','+ 18 meses','789648413096-7','Personagens','PLAY&COLLECT','PLAYMI'),
('3097','Mileva Disney Ariel','Mileva Disney Ariel','Mileva','Ao ar livre','','+ 18 meses','789648413097-4','Personagens','PLAY&COLLECT','PLAYMI'),
('3098','Totokinha Marvel Spidey','Totokinha Marvel Spidey','Totokinha','Primeiros Passos e Montaria','','+ 18 meses','789648413098-1','Personagens','PLAY&COLLECT','PLAYMI'),
('3099','Mileva Marvel Spidey','Mileva Marvel Spidey','Mileva','Ar livre','','+ 18 meses','789648413099-8','Personagens','PLAY&COLLECT','PLAYMI'),
('3100','Little Figs Disney Stitch','Little Figs Disney Stitch','Miniaturas Dedoches','Vínil','','+ 3 anos','789648413100-1','Personagens','PLAY&COLLECT','PLAYMI'),
('3101','Little Figs O Show da Luna','Little Figs O Show da Luna','Miniaturas Dedoches','Vínil','','+ 3 anos','789648413101-8','Personagens','PLAY&COLLECT','PLAYMI'),
('3102','Boneca Luna - O Show da Luna','Boneca Luna - O Show da Luna','','Vínil','','+ 18 meses','789648413102-5','Personagens','PLAY&COLLECT','PLAYMI'),
('3103','Little Figs Marvel Spidey','Little Figs Marvel Spidey','Miniaturas Dedoches','Vínil','','+ 3 anos','789648413103-2','Personagens','PLAY&COLLECT','PLAYMI'),
('3104','Little Figs Galinha Pintadinha Temática','Miniaturas Galinha Pintadinha Temática','Miniaturas Dedoches','Vínil','','+ 3 anos','789648413104-9','Personagens','PLAY&COLLECT','PLAYMI'),
('3105','Little Figs Os Smurfs','Little Figs Os Smurfs','Miniaturas Dedoches','Vínil','','+ 3 anos','789648413105-6','Personagens','PLAY&COLLECT','PLAYMI'),
('3106','Boneco de Vinil Os Smurfs - Smurf','Boneco de Vinil Os Smurfs - Smurf','Boneco de Vinil','Vínil','','+ 18 meses','789648413106-3','Personagens','PLAY&COLLECT','PLAYMI'),
('3107','Boneco de Vinil Os Smurfs - Papai Smurf','Boneco de Vinil Os Smurfs - Papai Smurf','Boneco de Vinil','Vínil','','+ 18 meses','789648413107-0','Personagens','PLAY&COLLECT','PLAYMI'),
('3108','Boneco de Vinil Os Smurfs - Smurfette','Boneco de Vinil Os Smurfs - Smurfette','Boneco de Vinil','Vínil','','+ 18 meses','789648413108-7','Personagens','PLAY&COLLECT','PLAYMI'),
('3112','Totokinha Galinha Pintadinha Mini','Totokinha Galinha Pintadinha Mini','Totokinha Galinha Pintadinha Mini','Primeiros Passos e Montaria','','+ 18 meses','789648413112-4','Personagens','PLAY&COLLECT','PLAYMI'),
('3113','Little Figs Bluey','Lançamento 2026','Miniaturas Dedoches','Boneco de vinil','','+ 3 anos','789648413113-1','Personagens','PLAY&COLLECT','PLAYMI'),
('3115','Boneca Luna Joaninha - O Show da Luna','Boneca Luna Joaninha - O Show da Luna','','Vínil','','+ 18 meses','789648413115-5','Personagens','PLAY&COLLECT','PLAYMI'),
('3116','Boneca Luna Melancia - O Show da Luna','Boneca Luna Melancia - O Show da Luna','','Vínil','','+ 18 meses','789648413116-2','Personagens','PLAY&COLLECT','PLAYMI'),
('3117','Little Figs Disney Toy Story','Lançamento 2026','Miniaturas Dedoches','Vínil','','+ 3 Anos','789648413117-9','Personagens','PLAY&COLLECT','PLAYMI'),
('3118','Boneco de Banho com Esguicho Disney Mickey','Boneco de Vinil com Esguicho Disney Mickey','Boneco de Banho com Esguicho','Boneco de vinil','','+ 9 meses','789648413118-6','Personagens','PLAY&COLLECT','PLAYMI'),
('3119','Boneco de Banho com Esguicho Disney Minnie','Boneco de Vinil com Esguicho Disney Minnie','Boneco de Banho com Esguicho','Boneco de vinil','','+ 9 meses','789648413119-3','Personagens','PLAY&COLLECT','PLAYMI'),
('3120','Boneco de Banho com Esguicho Disney Buzz Lightyear','Boneco de Vinil com Esguicho Disney Buzz Lightyear','Boneco de Banho com Esguicho','Boneco de vinil','','+ 9 meses','789648413120-9','Personagens','PLAY&COLLECT','PLAYMI'),
('3121','Boneco de Banho com Esguicho Disney Woody','Boneco de Vinil com Esguicho Disney Woody','Boneco de Banho com Esguicho','Boneco de vinil','','+ 9 meses','789648413121-6','Personagens','PLAY&COLLECT','PLAYMI'),
('3122','Little Figs Galinha Pintadinha O Filme','Lançamento 2026','Miniaturas Dedoches','Boneco de vinil','','+ 3 anos','789648413122-3','Personagens','PLAY&COLLECT','PLAYMI'),
('3123','Totokinha Bluey','Lançamento 2026','Totokinha','Primeiros Passos e Montaria','','+ 18 meses','789648413123-0','Personagens','PLAY&COLLECT','PLAYMI'),
('3124','Totokinha Disney Princesas','Lançamento 2026','Totokinha','Primeiros Passos','','+ 18 meses','789648413124-7','Personagens','PLAY&COLLECT','PLAYMI'),
('4009','Tópi Tambor','Tópi Tambor (Tambor de Plástico)','Tambor','Instrumentos Musicais','','+ 3 Anos','789648414009-6','PRIMEIRA INFÂNCIA','','TÓPI'),
('4010','Tópi Tamborete','Tópi Tamborete (Tamboretede Plástico)','Tamborete','Instrumentos Musicais','','+ 3 Anos','789648414010-2','PRIMEIRA INFÂNCIA','','TÓPI'),
('4012','Tópi Pandeiro','Tópi Pandeiro','Pandeiro','Instrumentos Musicais','','+ 3 Anos','789648414012-6','PRIMEIRA INFÂNCIA','','TÓPI'),
('4013','Tópi Dino Sabidinho','Tópi Dino Sabidinho (Carrinho Didático de Plástico)','Dino Sabidinho','Didáticos','','+ 18 meses','789648414013-3','PRIMEIRA INFÂNCIA','','TÓPI'),
('4014','Tópi Tortuga','Tópi Tortuga (Tartaruga Didática de Plástico)','Tortuga','Didáticos','','+ 18 meses','789648414014-0','PRIMEIRA INFÂNCIA','','TÓPI'),
('4015','Tópi Pata Bota Ovo','Tópi Pata Bota Ovo (Pato Didáticode Plástico)','Pata Bota Ovo','Didáticos','','+ 18 meses','789648414015-7','PRIMEIRA INFÂNCIA','','TÓPI'),
('4016','Tópi Mileva','Tópi Mileva (Carrinho De Puxar de Plástico)','Mileva','Didáticos','','+ 18 meses','789648414016-4','PRIMEIRA INFÂNCIA','','TÓPI'),
('4018','Tópi Invictus Caçamba','Tópi Invictus Caçamba (Caminhão de Plástico)','nvictus Caçamba','Didáticos','','+ 3 Anos','789648414018-8','RODA LIVRE','','TÓPI'),
('4019','Tópi Batedeira','Tópi Batedeira (Batedeira de Plástico)','Batedeira','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648414019-5','FAZ DE CONTA','','TÓPI'),
('4020','Tópi Liquidificador','Tópi Liquidificador (Liquidificador de Plástico)','Liquidificador','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648414020-1','FAZ DE CONTA','','TÓPI'),
('4021','Tópi Fogãozinho','Tópi Fogãozinho (Fogão de Plástico)','Fogãozinho','Cozinhas, Kits e Acessórios','','+ 3 Anos','789648414021-8','FAZ DE CONTA','','TÓPI'),
('4022','Tópi Trator Escavadeira','Tópi Trator Escavadeira','Trator Escavadeira','Tratores','','+ 3 Anos','789648414022-5','RODA LIVRE','','TÓPI'),
('4023','Tópi Trator Retroescavadeira','Tópi Trator Retroescavadeira','Trator Retroescavadeira','Tratores','','+ 3 Anos','789648414023-2','RODA LIVRE','','TÓPI'),
('4024','Tópi Trator Agro','Tópi Trator Agro','Trator Agro','Tratores','','+ 3 Anos','789648414024-9','RODA LIVRE','','TÓPI'),
('4025','Tópi Invictus Graneleiro','Tópi Invictus Graneleiro','Invictus Graneleiro','Caminhões Roda Livre','','+ 3 Anos','789648414025-6','RODA LIVRE','','TÓPI'),
('4026','Tópi Cestinha Didática','Tópi Cestinha Didática','TCestinha Didática','Didáticos','','+ 18 meses','789648414026-3','PRIMEIRA INFÂNCIA','','TÓPI'),
('4028','Tópi Combo Costruction','Tópi Combo Costruction','Combo Costruction','Caminhões Roda Livre','','+ 3 Anos','789648414028-7','RODA LIVRE','','TÓPI'),
('4029','Tópi Invictus Super Cegonheiro','Tópi Invictus Super Cegonheiro','Invictus Super Cegonheiro','Caminhões Roda Livre','','+ 3 Anos','789648414029-4','RODA LIVRE','','TÓPI'),
('4030','Tópi Bolofante com Formas Geométricas','Tópi Bolofante com Formas Geométricas','Bolofante','Didáticos','','+ 18 meses','789648414030-0','PRIMEIRA INFÂNCIA','','TÓPI'),
('4031','Tópi Bololéo com Letras','Tópi Bololéo com Letras','Bololéo','Didáticos','','+ 18 meses','789648414031-7','PRIMEIRA INFÂNCIA','','TÓPI'),
('4032','Tópi Bolpotamo com Numeros','Tópi Bolpotamo com Numeros','Bolpotamo','Didáticos','','+ 18 meses','789648414032-4','PRIMEIRA INFÂNCIA','','TÓPI'),
('6005','Totokinha Bolinha Rosa Caixa Individual','Totokinha Bolinha Rosa Caixa Individual','Totokinha Bolinha','Primeiros Passos','','+ 18 meses','789648416005-6','Montaria','PLAY&RIDE','PLAYMI'),
('6006','Totokinha Bolinha Azul Caixa  Individual','Totokinha Bolinha Azul Caixa Individual','Totokinha Bolinha','Primeiros Passos','','+ 18 meses','789648416006-3','Montaria','PLAY&RIDE','PLAYMI'),
('6007','Totoka Plus sem Eletrônico Rosa Caixa Individual','Totoka Plus sem Eletrônico Rosa Caixa Individual','Totoka Plus','Primeiros Passos','','+ 18 meses','789648416007-0','Montaria','PLAY&RIDE','PLAYMI'),
('6008','Totoka Plus sem Eletrônico Azul Caixa Individual','Totoka Plus sem Eletrônico Azul Caixa Individual','Totoka Plus','Primeiros Passos','','+ 18 meses','789648416008-7','Montaria','PLAY&RIDE','PLAYMI'),
('6009','Totoka Plus Baby Tractor Caixa  Individual','Totoka Plus Baby Tractor Caixa  Individual','Totoka Plus','Primeiros Passos','','+ 18 meses','789648416009-4','Montaria','PLAY&RIDE','PLAYMI'),
('6010','Totokinha Sport Rosa Caixa Individual','Totokinha Sport Rosa Caixa Individual','Totokinha Sport','Primeiros Passos','','+ 18 meses','789648416010-0','Montaria','PLAY&RIDE','PLAYMI')
on conflict (ref) do update set cadastro=excluded.cadastro, nome_antigo=excluded.nome_antigo, nome_embalagem=excluded.nome_embalagem, sub_categoria=excluded.sub_categoria, nome_tecnico=excluded.nome_tecnico, idade=excluded.idade, ean=excluded.ean, categoria=excluded.categoria, linha=excluded.linha, marca=excluded.marca;